package(default_visibility = ["//kythe:default_visibility"])

filegroup(
    name = "extractrepo",
    srcs = ["//kythe/go/platform/tools/extraction/extractrepo"],
)

filegroup(
    name = "repotester",
    srcs = ["//kythe/go/platform/tools/extraction/repotester"],
)
