// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kythe/proto/status_service.proto

package status_service_go_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusReply_Language_Support int32

const (
	StatusReply_Language_UNSUPPORTED  StatusReply_Language_Support = 0
	StatusReply_Language_EXPERIMENTAL StatusReply_Language_Support = 1
	StatusReply_Language_SUPPORTED    StatusReply_Language_Support = 2
)

var StatusReply_Language_Support_name = map[int32]string{
	0: "UNSUPPORTED",
	1: "EXPERIMENTAL",
	2: "SUPPORTED",
}

var StatusReply_Language_Support_value = map[string]int32{
	"UNSUPPORTED":  0,
	"EXPERIMENTAL": 1,
	"SUPPORTED":    2,
}

func (x StatusReply_Language_Support) String() string {
	return proto.EnumName(StatusReply_Language_Support_name, int32(x))
}

func (StatusReply_Language_Support) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a6ff3b5f197dffee, []int{1, 1, 0}
}

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6ff3b5f197dffee, []int{0}
}

func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusReply struct {
	Origins              []*StatusReply_Origin   `protobuf:"bytes,1,rep,name=origins,proto3" json:"origins,omitempty"`
	Languages            []*StatusReply_Language `protobuf:"bytes,2,rep,name=languages,proto3" json:"languages,omitempty"`
	IndexVersion         string                  `protobuf:"bytes,3,opt,name=index_version,json=indexVersion,proto3" json:"index_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *StatusReply) Reset()         { *m = StatusReply{} }
func (m *StatusReply) String() string { return proto.CompactTextString(m) }
func (*StatusReply) ProtoMessage()    {}
func (*StatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6ff3b5f197dffee, []int{1}
}

func (m *StatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusReply.Unmarshal(m, b)
}
func (m *StatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusReply.Marshal(b, m, deterministic)
}
func (m *StatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusReply.Merge(m, src)
}
func (m *StatusReply) XXX_Size() int {
	return xxx_messageInfo_StatusReply.Size(m)
}
func (m *StatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_StatusReply proto.InternalMessageInfo

func (m *StatusReply) GetOrigins() []*StatusReply_Origin {
	if m != nil {
		return m.Origins
	}
	return nil
}

func (m *StatusReply) GetLanguages() []*StatusReply_Language {
	if m != nil {
		return m.Languages
	}
	return nil
}

func (m *StatusReply) GetIndexVersion() string {
	if m != nil {
		return m.IndexVersion
	}
	return ""
}

type StatusReply_Origin struct {
	Corpus               string   `protobuf:"bytes,1,opt,name=corpus,proto3" json:"corpus,omitempty"`
	Revision             string   `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusReply_Origin) Reset()         { *m = StatusReply_Origin{} }
func (m *StatusReply_Origin) String() string { return proto.CompactTextString(m) }
func (*StatusReply_Origin) ProtoMessage()    {}
func (*StatusReply_Origin) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6ff3b5f197dffee, []int{1, 0}
}

func (m *StatusReply_Origin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusReply_Origin.Unmarshal(m, b)
}
func (m *StatusReply_Origin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusReply_Origin.Marshal(b, m, deterministic)
}
func (m *StatusReply_Origin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusReply_Origin.Merge(m, src)
}
func (m *StatusReply_Origin) XXX_Size() int {
	return xxx_messageInfo_StatusReply_Origin.Size(m)
}
func (m *StatusReply_Origin) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusReply_Origin.DiscardUnknown(m)
}

var xxx_messageInfo_StatusReply_Origin proto.InternalMessageInfo

func (m *StatusReply_Origin) GetCorpus() string {
	if m != nil {
		return m.Corpus
	}
	return ""
}

func (m *StatusReply_Origin) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

type StatusReply_Language struct {
	Name                 string                       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Support              StatusReply_Language_Support `protobuf:"varint,2,opt,name=support,proto3,enum=kythe.proto.StatusReply_Language_Support" json:"support,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *StatusReply_Language) Reset()         { *m = StatusReply_Language{} }
func (m *StatusReply_Language) String() string { return proto.CompactTextString(m) }
func (*StatusReply_Language) ProtoMessage()    {}
func (*StatusReply_Language) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6ff3b5f197dffee, []int{1, 1}
}

func (m *StatusReply_Language) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusReply_Language.Unmarshal(m, b)
}
func (m *StatusReply_Language) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusReply_Language.Marshal(b, m, deterministic)
}
func (m *StatusReply_Language) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusReply_Language.Merge(m, src)
}
func (m *StatusReply_Language) XXX_Size() int {
	return xxx_messageInfo_StatusReply_Language.Size(m)
}
func (m *StatusReply_Language) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusReply_Language.DiscardUnknown(m)
}

var xxx_messageInfo_StatusReply_Language proto.InternalMessageInfo

func (m *StatusReply_Language) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StatusReply_Language) GetSupport() StatusReply_Language_Support {
	if m != nil {
		return m.Support
	}
	return StatusReply_Language_UNSUPPORTED
}

func init() {
	proto.RegisterEnum("kythe.proto.StatusReply_Language_Support", StatusReply_Language_Support_name, StatusReply_Language_Support_value)
	proto.RegisterType((*StatusRequest)(nil), "kythe.proto.StatusRequest")
	proto.RegisterType((*StatusReply)(nil), "kythe.proto.StatusReply")
	proto.RegisterType((*StatusReply_Origin)(nil), "kythe.proto.StatusReply.Origin")
	proto.RegisterType((*StatusReply_Language)(nil), "kythe.proto.StatusReply.Language")
}

func init() {
	proto.RegisterFile("kythe/proto/status_service.proto", fileDescriptor_a6ff3b5f197dffee)
}

var fileDescriptor_a6ff3b5f197dffee = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcd, 0x6e, 0xaa, 0x40,
	0x14, 0xc7, 0x45, 0x6f, 0x50, 0x0f, 0x7a, 0x35, 0x67, 0x71, 0x2f, 0x61, 0xa3, 0xa5, 0x1b, 0xbb,
	0xc1, 0xc4, 0xae, 0xfa, 0x91, 0xf4, 0x93, 0x45, 0x13, 0xab, 0x16, 0xb4, 0x69, 0xba, 0x21, 0x54,
	0x27, 0x94, 0x14, 0x19, 0xca, 0x0c, 0xa4, 0x3e, 0x45, 0x5f, 0xa1, 0x8f, 0xda, 0x38, 0x40, 0xb5,
	0x49, 0x4d, 0x57, 0x70, 0xfe, 0xf3, 0xfb, 0x71, 0x0e, 0x39, 0x03, 0xdd, 0x97, 0x15, 0x7f, 0x26,
	0xfd, 0x28, 0xa6, 0x9c, 0xf6, 0x19, 0x77, 0x79, 0xc2, 0x1c, 0x46, 0xe2, 0xd4, 0x9f, 0x13, 0x43,
	0x84, 0xa8, 0x08, 0x22, 0x2b, 0xf4, 0x16, 0x34, 0x6d, 0x01, 0x59, 0xe4, 0x35, 0x21, 0x8c, 0xeb,
	0xef, 0x15, 0x50, 0x8a, 0x24, 0x0a, 0x56, 0x78, 0x04, 0x55, 0x1a, 0xfb, 0x9e, 0x1f, 0x32, 0x55,
	0xea, 0x56, 0x7a, 0xca, 0xa0, 0x63, 0x6c, 0xf9, 0xc6, 0x16, 0x6a, 0x8c, 0x05, 0x67, 0x15, 0x3c,
	0x9e, 0x41, 0x3d, 0x70, 0x43, 0x2f, 0x71, 0x3d, 0xc2, 0xd4, 0xb2, 0x90, 0xf7, 0x76, 0xca, 0xc3,
	0x9c, 0xb4, 0x36, 0x0e, 0xee, 0x43, 0xd3, 0x0f, 0x17, 0xe4, 0xcd, 0x49, 0x49, 0xcc, 0x7c, 0x1a,
	0xaa, 0x95, 0xae, 0xd4, 0xab, 0x5b, 0x0d, 0x11, 0xde, 0x67, 0x99, 0x76, 0x0a, 0x72, 0xd6, 0x18,
	0xff, 0x81, 0x3c, 0xa7, 0x71, 0x94, 0xac, 0x27, 0x5d, 0x73, 0x79, 0x85, 0x1a, 0xd4, 0x62, 0x92,
	0xfa, 0xe2, 0x0b, 0x65, 0x71, 0xf2, 0x55, 0x6b, 0x1f, 0x12, 0xd4, 0x8a, 0xd6, 0x88, 0xf0, 0x27,
	0x74, 0x97, 0x24, 0xd7, 0xc5, 0x3b, 0x5e, 0x41, 0x95, 0x25, 0x51, 0x44, 0x63, 0x2e, 0xdc, 0xbf,
	0x83, 0x83, 0x5f, 0x7f, 0xc1, 0xb0, 0x33, 0xc1, 0x2a, 0x4c, 0xfd, 0x04, 0xaa, 0x79, 0x86, 0x2d,
	0x50, 0x66, 0x23, 0x7b, 0x36, 0x99, 0x8c, 0xad, 0xa9, 0x79, 0xdd, 0x2e, 0x61, 0x1b, 0x1a, 0xe6,
	0xc3, 0xc4, 0xb4, 0x6e, 0x6e, 0xcd, 0xd1, 0xf4, 0x62, 0xd8, 0x96, 0xb0, 0x09, 0xf5, 0x0d, 0x50,
	0x1e, 0xdc, 0x15, 0x2b, 0xb2, 0xb3, 0x35, 0xe2, 0x39, 0xc8, 0x59, 0x80, 0xda, 0x8f, 0xb3, 0x88,
	0x45, 0x6a, 0xea, 0xae, 0x39, 0xf5, 0xd2, 0xe5, 0x31, 0x74, 0xe6, 0x74, 0x69, 0x78, 0x94, 0x7a,
	0x01, 0x31, 0x16, 0x24, 0xe5, 0x94, 0x06, 0x6c, 0x5b, 0x78, 0xfc, 0xff, 0xfd, 0xee, 0x38, 0x1e,
	0x75, 0xc4, 0xc1, 0x93, 0x2c, 0x1e, 0x87, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x67, 0x79, 0x74,
	0x20, 0x69, 0x02, 0x00, 0x00,
}
