// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: kythe/proto/bazel_artifact_selector_v2.proto

package bazel_artifact_selector_v2_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BazelAspectArtifactSelectorStateV2 struct {
	state         protoimpl.MessageState                                `protogen:"open.v1"`
	Files         []*BazelAspectArtifactSelectorStateV2_File            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	FileSets      map[int64]*BazelAspectArtifactSelectorStateV2_FileSet `protobuf:"bytes,2,rep,name=file_sets,json=fileSets,proto3" json:"file_sets,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Disposed      []int64                                               `protobuf:"varint,3,rep,packed,name=disposed,proto3" json:"disposed,omitempty"`
	Pending       map[int64]string                                      `protobuf:"bytes,4,rep,name=pending,proto3" json:"pending,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FileSetIds    []string                                              `protobuf:"bytes,5,rep,name=file_set_ids,json=fileSetIds,proto3" json:"file_set_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BazelAspectArtifactSelectorStateV2) Reset() {
	*x = BazelAspectArtifactSelectorStateV2{}
	mi := &file_kythe_proto_bazel_artifact_selector_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BazelAspectArtifactSelectorStateV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BazelAspectArtifactSelectorStateV2) ProtoMessage() {}

func (x *BazelAspectArtifactSelectorStateV2) ProtoReflect() protoreflect.Message {
	mi := &file_kythe_proto_bazel_artifact_selector_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BazelAspectArtifactSelectorStateV2.ProtoReflect.Descriptor instead.
func (*BazelAspectArtifactSelectorStateV2) Descriptor() ([]byte, []int) {
	return file_kythe_proto_bazel_artifact_selector_v2_proto_rawDescGZIP(), []int{0}
}

func (x *BazelAspectArtifactSelectorStateV2) GetFiles() []*BazelAspectArtifactSelectorStateV2_File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *BazelAspectArtifactSelectorStateV2) GetFileSets() map[int64]*BazelAspectArtifactSelectorStateV2_FileSet {
	if x != nil {
		return x.FileSets
	}
	return nil
}

func (x *BazelAspectArtifactSelectorStateV2) GetDisposed() []int64 {
	if x != nil {
		return x.Disposed
	}
	return nil
}

func (x *BazelAspectArtifactSelectorStateV2) GetPending() map[int64]string {
	if x != nil {
		return x.Pending
	}
	return nil
}

func (x *BazelAspectArtifactSelectorStateV2) GetFileSetIds() []string {
	if x != nil {
		return x.FileSetIds
	}
	return nil
}

type BazelAspectArtifactSelectorStateV2_File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalPath     string                 `protobuf:"bytes,1,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	Uri           string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BazelAspectArtifactSelectorStateV2_File) Reset() {
	*x = BazelAspectArtifactSelectorStateV2_File{}
	mi := &file_kythe_proto_bazel_artifact_selector_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BazelAspectArtifactSelectorStateV2_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BazelAspectArtifactSelectorStateV2_File) ProtoMessage() {}

func (x *BazelAspectArtifactSelectorStateV2_File) ProtoReflect() protoreflect.Message {
	mi := &file_kythe_proto_bazel_artifact_selector_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BazelAspectArtifactSelectorStateV2_File.ProtoReflect.Descriptor instead.
func (*BazelAspectArtifactSelectorStateV2_File) Descriptor() ([]byte, []int) {
	return file_kythe_proto_bazel_artifact_selector_v2_proto_rawDescGZIP(), []int{0, 0}
}

func (x *BazelAspectArtifactSelectorStateV2_File) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *BazelAspectArtifactSelectorStateV2_File) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type BazelAspectArtifactSelectorStateV2_FileSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []uint64               `protobuf:"varint,2,rep,packed,name=files,proto3" json:"files,omitempty"`
	FileSets      []int64                `protobuf:"varint,3,rep,packed,name=file_sets,json=fileSets,proto3" json:"file_sets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BazelAspectArtifactSelectorStateV2_FileSet) Reset() {
	*x = BazelAspectArtifactSelectorStateV2_FileSet{}
	mi := &file_kythe_proto_bazel_artifact_selector_v2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BazelAspectArtifactSelectorStateV2_FileSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BazelAspectArtifactSelectorStateV2_FileSet) ProtoMessage() {}

func (x *BazelAspectArtifactSelectorStateV2_FileSet) ProtoReflect() protoreflect.Message {
	mi := &file_kythe_proto_bazel_artifact_selector_v2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BazelAspectArtifactSelectorStateV2_FileSet.ProtoReflect.Descriptor instead.
func (*BazelAspectArtifactSelectorStateV2_FileSet) Descriptor() ([]byte, []int) {
	return file_kythe_proto_bazel_artifact_selector_v2_proto_rawDescGZIP(), []int{0, 1}
}

func (x *BazelAspectArtifactSelectorStateV2_FileSet) GetFiles() []uint64 {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *BazelAspectArtifactSelectorStateV2_FileSet) GetFileSets() []int64 {
	if x != nil {
		return x.FileSets
	}
	return nil
}

var File_kythe_proto_bazel_artifact_selector_v2_proto protoreflect.FileDescriptor

const file_kythe_proto_bazel_artifact_selector_v2_proto_rawDesc = "" +
	"\n" +
	",kythe/proto/bazel_artifact_selector_v2.proto\x12\vkythe.proto\"\x8b\x05\n" +
	"\"BazelAspectArtifactSelectorStateV2\x12J\n" +
	"\x05files\x18\x01 \x03(\v24.kythe.proto.BazelAspectArtifactSelectorStateV2.FileR\x05files\x12Z\n" +
	"\tfile_sets\x18\x02 \x03(\v2=.kythe.proto.BazelAspectArtifactSelectorStateV2.FileSetsEntryR\bfileSets\x12\x1a\n" +
	"\bdisposed\x18\x03 \x03(\x03R\bdisposed\x12V\n" +
	"\apending\x18\x04 \x03(\v2<.kythe.proto.BazelAspectArtifactSelectorStateV2.PendingEntryR\apending\x12 \n" +
	"\ffile_set_ids\x18\x05 \x03(\tR\n" +
	"fileSetIds\x1a7\n" +
	"\x04File\x12\x1d\n" +
	"\n" +
	"local_path\x18\x01 \x01(\tR\tlocalPath\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x1a<\n" +
	"\aFileSet\x12\x14\n" +
	"\x05files\x18\x02 \x03(\x04R\x05files\x12\x1b\n" +
	"\tfile_sets\x18\x03 \x03(\x03R\bfileSets\x1at\n" +
	"\rFileSetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12M\n" +
	"\x05value\x18\x02 \x01(\v27.kythe.proto.BazelAspectArtifactSelectorStateV2.FileSetR\x05value:\x028\x01\x1a:\n" +
	"\fPendingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B<P\x01Z8kythe.io/kythe/proto/bazel_artifact_selector_v2_go_protob\x06proto3"

var (
	file_kythe_proto_bazel_artifact_selector_v2_proto_rawDescOnce sync.Once
	file_kythe_proto_bazel_artifact_selector_v2_proto_rawDescData []byte
)

func file_kythe_proto_bazel_artifact_selector_v2_proto_rawDescGZIP() []byte {
	file_kythe_proto_bazel_artifact_selector_v2_proto_rawDescOnce.Do(func() {
		file_kythe_proto_bazel_artifact_selector_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kythe_proto_bazel_artifact_selector_v2_proto_rawDesc), len(file_kythe_proto_bazel_artifact_selector_v2_proto_rawDesc)))
	})
	return file_kythe_proto_bazel_artifact_selector_v2_proto_rawDescData
}

var file_kythe_proto_bazel_artifact_selector_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_kythe_proto_bazel_artifact_selector_v2_proto_goTypes = []any{
	(*BazelAspectArtifactSelectorStateV2)(nil),         // 0: kythe.proto.BazelAspectArtifactSelectorStateV2
	(*BazelAspectArtifactSelectorStateV2_File)(nil),    // 1: kythe.proto.BazelAspectArtifactSelectorStateV2.File
	(*BazelAspectArtifactSelectorStateV2_FileSet)(nil), // 2: kythe.proto.BazelAspectArtifactSelectorStateV2.FileSet
	nil, // 3: kythe.proto.BazelAspectArtifactSelectorStateV2.FileSetsEntry
	nil, // 4: kythe.proto.BazelAspectArtifactSelectorStateV2.PendingEntry
}
var file_kythe_proto_bazel_artifact_selector_v2_proto_depIdxs = []int32{
	1, // 0: kythe.proto.BazelAspectArtifactSelectorStateV2.files:type_name -> kythe.proto.BazelAspectArtifactSelectorStateV2.File
	3, // 1: kythe.proto.BazelAspectArtifactSelectorStateV2.file_sets:type_name -> kythe.proto.BazelAspectArtifactSelectorStateV2.FileSetsEntry
	4, // 2: kythe.proto.BazelAspectArtifactSelectorStateV2.pending:type_name -> kythe.proto.BazelAspectArtifactSelectorStateV2.PendingEntry
	2, // 3: kythe.proto.BazelAspectArtifactSelectorStateV2.FileSetsEntry.value:type_name -> kythe.proto.BazelAspectArtifactSelectorStateV2.FileSet
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_kythe_proto_bazel_artifact_selector_v2_proto_init() }
func file_kythe_proto_bazel_artifact_selector_v2_proto_init() {
	if File_kythe_proto_bazel_artifact_selector_v2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kythe_proto_bazel_artifact_selector_v2_proto_rawDesc), len(file_kythe_proto_bazel_artifact_selector_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kythe_proto_bazel_artifact_selector_v2_proto_goTypes,
		DependencyIndexes: file_kythe_proto_bazel_artifact_selector_v2_proto_depIdxs,
		MessageInfos:      file_kythe_proto_bazel_artifact_selector_v2_proto_msgTypes,
	}.Build()
	File_kythe_proto_bazel_artifact_selector_v2_proto = out.File
	file_kythe_proto_bazel_artifact_selector_v2_proto_goTypes = nil
	file_kythe_proto_bazel_artifact_selector_v2_proto_depIdxs = nil
}
