load("//tools/build_rules/go", "go_package")

package(default_visibility = ["//kythe:default_visibility"])

go_package(
    deps = [
        "//kythe/go/services/graphstore",
        "//kythe/go/services/graphstore/proxy",
        "//kythe/go/storage/inmemory",
        "//kythe/go/storage/leveldb",
        "//kythe/go/storage/sql",
    ],
)
