#!/bin/bash -e

# Copyright 2015 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# campfire-docker will build/run the google/kythe-campfire Docker container,
# passing all arguments to campfire. See ./campfire help for its commands.

cd "$(dirname "$0")"

error() { echo -e "\e[0;31mERROR:\e[m $@" >&2; exit 1; }
info() { echo -e "\e[0;32mINFO:\e[m $@" >&2; }

if ! command -v docker &>/dev/null; then
  error "docker binary not found
Please see https://docs.docker.com/installation/ for installation instructions."
fi

if ! docker images | grep '^google/kythe-campfire\s' >/dev/null; then
  info "missing campfire docker image"
  ./campfire package //buildtools/docker
fi

INTERACTIVE=-i
DOCKER_FLAGS=(--rm -t -v "$PWD:/repo")
CAMPFIRE_ARGS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --non-interactive)
      INTERACTIVE= ;;
    -v)
      DOCKER_FLAGS+=("$1" "$2")
      shift ;;
    *)
      CAMPFIRE_ARGS+=("$1") ;;
  esac
  shift
done

docker run "${DOCKER_FLAGS[@]}" $INTERACTIVE google/kythe-campfire "${CAMPFIRE_ARGS[@]}"
