#!/bin/sh -e
# Copyright 2015 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
ROOT="$(readlink -e "$(dirname $0)")"
NODEDIR="${NODEDIR:-$ROOT/third_party/node/bin/}"

if [ ! -d "$ROOT/buildtools/node_modules" ]; then
  cd "$ROOT/buildtools"
  "$NODEDIR/node" "$NODEDIR/npm" install
  cd -
fi

case "$1" in
  build|test|run|bench|extract|package)
    "$ROOT/buildtools/check_modules.sh" \
      "$NODEDIR/node $ROOT/buildtools/main query_config"
  ;;
esac
exec "$NODEDIR/node" "$ROOT/buildtools/main" "$@"
