package(default_visibility = ["//kythe:default_visibility"])

java_library(
    name = "indexpack",
    srcs = [
        "Archive.java",
    ],
    deps = [
        "//external:gson",
        "//external:guava",
        "//external:proto/protobuf_java",
        "//kythe/java/com/google/devtools/kythe/extractors/shared",
        "//kythe/java/com/google/devtools/kythe/util:json",
        "//kythe/proto:analysis_proto_java",
    ],
)
