package(default_visibility = ["//visibility:public"])

java_library(
    name = "indexpack",
    srcs = [
        "Archive.java",
    ],
    deps = [
        "//kythe/java/com/google/devtools/kythe/extractors/shared",
        "//kythe/java/com/google/devtools/kythe/util:json",
        "//kythe/proto:analysis_proto",
        "//third_party:protobuf",
        "//third_party/gson",
        "//third_party/guava",
    ],
)
