load("//tools/build_rules/go", "go_library")

package(default_visibility = ["//kythe:default_visibility"])

go_library(
    name = "files",
    srcs = [
        "files.go",
    ],
    deps = [
        "//kythe/proto:analysis_proto",
    ],
)
