load("//tools:build_rules/go.bzl", "go_package_library")

package(default_visibility = ["//kythe:default_visibility"])

go_package_library(
    name = "files",
    srcs = ["files.go"],
    deps = ["//kythe/proto:analysis_proto_go"],
)
