java_test(
    name = "stream_fact_emitter_test",
    size = "small",
    srcs = ["StreamFactEmitterTest.java"],
    test_class = "com.google.devtools.kythe.analyzers.base.StreamFactEmitterTest",
    deps = [
        "//kythe/java/com/google/devtools/kythe/analyzers/base:stream_fact_emitter",
        "//kythe/proto:storage_proto_java",
        "@com_google_truth_truth//jar",
        "@junit_junit//jar",
    ],
)
