load("//tools:build_rules/go.bzl", "go_package_library")

package(default_visibility = ["//kythe:default_visibility"])

go_package_library(
    name = "testutil",
    srcs = ["testutil.go"],
    deps = ["@go_protobuf//:proto"],
)
