# Cloud Build configuration for mandatory presubmit tests.
steps:
  - name: gcr.io/kythe-repo/bazelisk-builder-client
    id: bazel-minversion
    env:
      - USE_BAZEL_VERSION=min
    args:
      - bazel
      - test
      - '--config=remote'
      - //...
  - name: gcr.io/kythe-repo/bazelisk-builder-client
    id: bazel
    args:
      - bazel
      - test
      - '--config=remote'
      - //...
  - name: gcr.io/kythe-repo/bazelisk-builder-client
    id: bazel-release
    args:
      - bazel
      - test
      - '--config=remote'
      - '-c'
      - opt
      - '--stamp'
      - //...
      - //kythe/docs/schema
      - '//kythe/release:release_test'
  - name: gcr.io/kythe-repo/go-builder
    id: go-module
    args:
      - go
      - test
      - '-mod=readonly'
      - ./kythe/...
    waitFor:
      - '-'  # go test can run concurrently with the bazel tests.
timeout: 1800s
options:
  # The increased scheduling time is more than offset by the substantially improved test runtime.
  machineType: E2_HIGHCPU_8
