package(default_visibility = ["//kythe:default_visibility"])

exports_files([
    "empty.kzip",
    "garbage_unit.kzip",
    "malformed.kzip",
    "missing-unit.kzip",
    "missing-pbunit.kzip",
    "stringset.kzip",
    "stringset_with_empty_file.kzip",
    "56bf5044e1b5c4c1cc7c4b131ac2fb979d288460e63352b10eef80ca35bd0a7b.pbtxt",
    "bb761979683e7c268e967eb5bcdedaa7fa5d1d472b0826b00b69acafbaad7ee6.pbtxt",
    "e9e170dcfca53c8126755bbc8b703994dedd3af32584291e01fba164ab5d3f32.pbtxt",
])
