// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: kythe/proto/explore.proto

package explore_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common_go_proto "kythe.io/kythe/proto/common_go_proto"
	storage_go_proto "kythe.io/kythe/proto/storage_go_proto"
	xref_go_proto "kythe.io/kythe/proto/xref_go_proto"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeData struct {
	state            protoimpl.MessageState        `protogen:"open.v1"`
	Kind             string                        `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Subkind          string                        `protobuf:"bytes,2,opt,name=subkind,proto3" json:"subkind,omitempty"`
	Locations        []*xref_go_proto.Location     `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`
	DefinitionAnchor string                        `protobuf:"bytes,4,opt,name=definition_anchor,json=definitionAnchor,proto3" json:"definition_anchor,omitempty"`
	Code             *common_go_proto.MarkedSource `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeData) Reset() {
	*x = NodeData{}
	mi := &file_kythe_proto_explore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeData) ProtoMessage() {}

func (x *NodeData) ProtoReflect() protoreflect.Message {
	mi := &file_kythe_proto_explore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeData.ProtoReflect.Descriptor instead.
func (*NodeData) Descriptor() ([]byte, []int) {
	return file_kythe_proto_explore_proto_rawDescGZIP(), []int{0}
}

func (x *NodeData) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *NodeData) GetSubkind() string {
	if x != nil {
		return x.Subkind
	}
	return ""
}

func (x *NodeData) GetLocations() []*xref_go_proto.Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *NodeData) GetDefinitionAnchor() string {
	if x != nil {
		return x.DefinitionAnchor
	}
	return ""
}

func (x *NodeData) GetCode() *common_go_proto.MarkedSource {
	if x != nil {
		return x.Code
	}
	return nil
}

type GraphNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeData      *NodeData              `protobuf:"bytes,1,opt,name=node_data,json=nodeData,proto3" json:"node_data,omitempty"`
	Predecessors  []string               `protobuf:"bytes,2,rep,name=predecessors,proto3" json:"predecessors,omitempty"`
	Successors    []string               `protobuf:"bytes,3,rep,name=successors,proto3" json:"successors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphNode) Reset() {
	*x = GraphNode{}
	mi := &file_kythe_proto_explore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNode) ProtoMessage() {}

func (x *GraphNode) ProtoReflect() protoreflect.Message {
	mi := &file_kythe_proto_explore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNode.ProtoReflect.Descriptor instead.
func (*GraphNode) Descriptor() ([]byte, []int) {
	return file_kythe_proto_explore_proto_rawDescGZIP(), []int{1}
}

func (x *GraphNode) GetNodeData() *NodeData {
	if x != nil {
		return x.NodeData
	}
	return nil
}

func (x *GraphNode) GetPredecessors() []string {
	if x != nil {
		return x.Predecessors
	}
	return nil
}

func (x *GraphNode) GetSuccessors() []string {
	if x != nil {
		return x.Successors
	}
	return nil
}

type Graph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         map[string]*GraphNode  `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Graph) Reset() {
	*x = Graph{}
	mi := &file_kythe_proto_explore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Graph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graph) ProtoMessage() {}

func (x *Graph) ProtoReflect() protoreflect.Message {
	mi := &file_kythe_proto_explore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graph.ProtoReflect.Descriptor instead.
func (*Graph) Descriptor() ([]byte, []int) {
	return file_kythe_proto_explore_proto_rawDescGZIP(), []int{2}
}

func (x *Graph) GetNodes() map[string]*GraphNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodeFilter struct {
	state             protoimpl.MessageState    `protogen:"open.v1"`
	IncludedLanguages []string                  `protobuf:"bytes,1,rep,name=included_languages,json=includedLanguages,proto3" json:"included_languages,omitempty"`
	IncludedFiles     []*storage_go_proto.VName `protobuf:"bytes,2,rep,name=included_files,json=includedFiles,proto3" json:"included_files,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeFilter) Reset() {
	*x = NodeFilter{}
	mi := &file_kythe_proto_explore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeFilter) ProtoMessage() {}

func (x *NodeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_kythe_proto_explore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeFilter.ProtoReflect.Descriptor instead.
func (*NodeFilter) Descriptor() ([]byte, []int) {
	return file_kythe_proto_explore_proto_rawDescGZIP(), []int{3}
}

func (x *NodeFilter) GetIncludedLanguages() []string {
	if x != nil {
		return x.IncludedLanguages
	}
	return nil
}

func (x *NodeFilter) GetIncludedFiles() []*storage_go_proto.VName {
	if x != nil {
		return x.IncludedFiles
	}
	return nil
}

type Tickets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []string               `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tickets) Reset() {
	*x = Tickets{}
	mi := &file_kythe_proto_explore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tickets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tickets) ProtoMessage() {}

func (x *Tickets) ProtoReflect() protoreflect.Message {
	mi := &file_kythe_proto_explore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tickets.ProtoReflect.Descriptor instead.
func (*Tickets) Descriptor() ([]byte, []int) {
	return file_kythe_proto_explore_proto_rawDescGZIP(), []int{4}
}

func (x *Tickets) GetTickets() []string {
	if x != nil {
		return x.Tickets
	}
	return nil
}

type TypeHierarchyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeTicket    string                 `protobuf:"bytes,1,opt,name=type_ticket,json=typeTicket,proto3" json:"type_ticket,omitempty"`
	NodeFilter    *NodeFilter            `protobuf:"bytes,2,opt,name=node_filter,json=nodeFilter,proto3" json:"node_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeHierarchyRequest) Reset() {
	*x = TypeHierarchyRequest{}
	mi := &file_kythe_proto_explore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeHierarchyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeHierarchyRequest) ProtoMessage() {}

func (x *TypeHierarchyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kythe_proto_explore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeHierarchyRequest.ProtoReflect.Descriptor instead.
func (*TypeHierarchyRequest) Descriptor() ([]byte, []int) {
	return file_kythe_proto_explore_proto_rawDescGZIP(), []int{5}
}

func (x *TypeHierarchyRequest) GetTypeTicket() string {
	if x != nil {
		return x.TypeTicket
	}
	return ""
}

func (x *TypeHierarchyRequest) GetNodeFilter() *NodeFilter {
	if x != nil {
		return x.NodeFilter
	}
	return nil
}

type TypeHierarchyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeTicket    string                 `protobuf:"bytes,1,opt,name=type_ticket,json=typeTicket,proto3" json:"type_ticket,omitempty"`
	Graph         *Graph                 `protobuf:"bytes,2,opt,name=graph,proto3" json:"graph,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeHierarchyReply) Reset() {
	*x = TypeHierarchyReply{}
	mi := &file_kythe_proto_explore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeHierarchyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeHierarchyReply) ProtoMessage() {}

func (x *TypeHierarchyReply) ProtoReflect() protoreflect.Message {
	mi := &file_kythe_proto_explore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeHierarchyReply.ProtoReflect.Descriptor instead.
func (*TypeHierarchyReply) Descriptor() ([]byte, []int) {
	return file_kythe_proto_explore_proto_rawDescGZIP(), []int{6}
}

func (x *TypeHierarchyReply) GetTypeTicket() string {
	if x != nil {
		return x.TypeTicket
	}
	return ""
}

func (x *TypeHierarchyReply) GetGraph() *Graph {
	if x != nil {
		return x.Graph
	}
	return nil
}

type CallersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []string               `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallersRequest) Reset() {
	*x = CallersRequest{}
	mi := &file_kythe_proto_explore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallersRequest) ProtoMessage() {}

func (x *CallersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kythe_proto_explore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallersRequest.ProtoReflect.Descriptor instead.
func (*CallersRequest) Descriptor() ([]byte, []int) {
	return file_kythe_proto_explore_proto_rawDescGZIP(), []int{7}
}

func (x *CallersRequest) GetTickets() []string {
	if x != nil {
		return x.Tickets
	}
	return nil
}

type CallersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Graph         *Graph                 `protobuf:"bytes,1,opt,name=graph,proto3" json:"graph,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallersReply) Reset() {
	*x = CallersReply{}
	mi := &file_kythe_proto_explore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallersReply) ProtoMessage() {}

func (x *CallersReply) ProtoReflect() protoreflect.Message {
	mi := &file_kythe_proto_explore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallersReply.ProtoReflect.Descriptor instead.
func (*CallersReply) Descriptor() ([]byte, []int) {
	return file_kythe_proto_explore_proto_rawDescGZIP(), []int{8}
}

func (x *CallersReply) GetGraph() *Graph {
	if x != nil {
		return x.Graph
	}
	return nil
}

type CalleesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []string               `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalleesRequest) Reset() {
	*x = CalleesRequest{}
	mi := &file_kythe_proto_explore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalleesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalleesRequest) ProtoMessage() {}

func (x *CalleesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kythe_proto_explore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalleesRequest.ProtoReflect.Descriptor instead.
func (*CalleesRequest) Descriptor() ([]byte, []int) {
	return file_kythe_proto_explore_proto_rawDescGZIP(), []int{9}
}

func (x *CalleesRequest) GetTickets() []string {
	if x != nil {
		return x.Tickets
	}
	return nil
}

type CalleesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Graph         *Graph                 `protobuf:"bytes,1,opt,name=graph,proto3" json:"graph,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalleesReply) Reset() {
	*x = CalleesReply{}
	mi := &file_kythe_proto_explore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalleesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalleesReply) ProtoMessage() {}

func (x *CalleesReply) ProtoReflect() protoreflect.Message {
	mi := &file_kythe_proto_explore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalleesReply.ProtoReflect.Descriptor instead.
func (*CalleesReply) Descriptor() ([]byte, []int) {
	return file_kythe_proto_explore_proto_rawDescGZIP(), []int{10}
}

func (x *CalleesReply) GetGraph() *Graph {
	if x != nil {
		return x.Graph
	}
	return nil
}

type ParametersRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FunctionTickets []string               `protobuf:"bytes,1,rep,name=function_tickets,json=functionTickets,proto3" json:"function_tickets,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ParametersRequest) Reset() {
	*x = ParametersRequest{}
	mi := &file_kythe_proto_explore_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParametersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParametersRequest) ProtoMessage() {}

func (x *ParametersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kythe_proto_explore_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParametersRequest.ProtoReflect.Descriptor instead.
func (*ParametersRequest) Descriptor() ([]byte, []int) {
	return file_kythe_proto_explore_proto_rawDescGZIP(), []int{11}
}

func (x *ParametersRequest) GetFunctionTickets() []string {
	if x != nil {
		return x.FunctionTickets
	}
	return nil
}

type ParametersReply struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	FunctionToParameters  map[string]*Tickets    `protobuf:"bytes,1,rep,name=function_to_parameters,json=functionToParameters,proto3" json:"function_to_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FunctionToReturnValue map[string]string      `protobuf:"bytes,2,rep,name=function_to_return_value,json=functionToReturnValue,proto3" json:"function_to_return_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NodeData              map[string]*NodeData   `protobuf:"bytes,3,rep,name=node_data,json=nodeData,proto3" json:"node_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ParametersReply) Reset() {
	*x = ParametersReply{}
	mi := &file_kythe_proto_explore_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParametersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParametersReply) ProtoMessage() {}

func (x *ParametersReply) ProtoReflect() protoreflect.Message {
	mi := &file_kythe_proto_explore_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParametersReply.ProtoReflect.Descriptor instead.
func (*ParametersReply) Descriptor() ([]byte, []int) {
	return file_kythe_proto_explore_proto_rawDescGZIP(), []int{12}
}

func (x *ParametersReply) GetFunctionToParameters() map[string]*Tickets {
	if x != nil {
		return x.FunctionToParameters
	}
	return nil
}

func (x *ParametersReply) GetFunctionToReturnValue() map[string]string {
	if x != nil {
		return x.FunctionToReturnValue
	}
	return nil
}

func (x *ParametersReply) GetNodeData() map[string]*NodeData {
	if x != nil {
		return x.NodeData
	}
	return nil
}

type ParentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []string               `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParentsRequest) Reset() {
	*x = ParentsRequest{}
	mi := &file_kythe_proto_explore_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentsRequest) ProtoMessage() {}

func (x *ParentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kythe_proto_explore_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentsRequest.ProtoReflect.Descriptor instead.
func (*ParentsRequest) Descriptor() ([]byte, []int) {
	return file_kythe_proto_explore_proto_rawDescGZIP(), []int{13}
}

func (x *ParentsRequest) GetTickets() []string {
	if x != nil {
		return x.Tickets
	}
	return nil
}

type ParentsReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InputToParents map[string]*Tickets    `protobuf:"bytes,1,rep,name=input_to_parents,json=inputToParents,proto3" json:"input_to_parents,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ParentsReply) Reset() {
	*x = ParentsReply{}
	mi := &file_kythe_proto_explore_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParentsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParentsReply) ProtoMessage() {}

func (x *ParentsReply) ProtoReflect() protoreflect.Message {
	mi := &file_kythe_proto_explore_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParentsReply.ProtoReflect.Descriptor instead.
func (*ParentsReply) Descriptor() ([]byte, []int) {
	return file_kythe_proto_explore_proto_rawDescGZIP(), []int{14}
}

func (x *ParentsReply) GetInputToParents() map[string]*Tickets {
	if x != nil {
		return x.InputToParents
	}
	return nil
}

type ChildrenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []string               `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChildrenRequest) Reset() {
	*x = ChildrenRequest{}
	mi := &file_kythe_proto_explore_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChildrenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildrenRequest) ProtoMessage() {}

func (x *ChildrenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kythe_proto_explore_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildrenRequest.ProtoReflect.Descriptor instead.
func (*ChildrenRequest) Descriptor() ([]byte, []int) {
	return file_kythe_proto_explore_proto_rawDescGZIP(), []int{15}
}

func (x *ChildrenRequest) GetTickets() []string {
	if x != nil {
		return x.Tickets
	}
	return nil
}

type ChildrenReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InputToChildren map[string]*Tickets    `protobuf:"bytes,1,rep,name=input_to_children,json=inputToChildren,proto3" json:"input_to_children,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChildrenReply) Reset() {
	*x = ChildrenReply{}
	mi := &file_kythe_proto_explore_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChildrenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildrenReply) ProtoMessage() {}

func (x *ChildrenReply) ProtoReflect() protoreflect.Message {
	mi := &file_kythe_proto_explore_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildrenReply.ProtoReflect.Descriptor instead.
func (*ChildrenReply) Descriptor() ([]byte, []int) {
	return file_kythe_proto_explore_proto_rawDescGZIP(), []int{16}
}

func (x *ChildrenReply) GetInputToChildren() map[string]*Tickets {
	if x != nil {
		return x.InputToChildren
	}
	return nil
}

var File_kythe_proto_explore_proto protoreflect.FileDescriptor

const file_kythe_proto_explore_proto_rawDesc = "" +
	"\n" +
	"\x19kythe/proto/explore.proto\x12\vkythe.proto\x1a\x18kythe/proto/common.proto\x1a\x19kythe/proto/storage.proto\x1a\x16kythe/proto/xref.proto\"\xd0\x01\n" +
	"\bNodeData\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\asubkind\x18\x02 \x01(\tR\asubkind\x123\n" +
	"\tlocations\x18\x03 \x03(\v2\x15.kythe.proto.LocationR\tlocations\x12+\n" +
	"\x11definition_anchor\x18\x04 \x01(\tR\x10definitionAnchor\x124\n" +
	"\x04code\x18\x05 \x01(\v2 .kythe.proto.common.MarkedSourceR\x04code\"\x83\x01\n" +
	"\tGraphNode\x122\n" +
	"\tnode_data\x18\x01 \x01(\v2\x15.kythe.proto.NodeDataR\bnodeData\x12\"\n" +
	"\fpredecessors\x18\x02 \x03(\tR\fpredecessors\x12\x1e\n" +
	"\n" +
	"successors\x18\x03 \x03(\tR\n" +
	"successors\"\x8e\x01\n" +
	"\x05Graph\x123\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1d.kythe.proto.Graph.NodesEntryR\x05nodes\x1aP\n" +
	"\n" +
	"NodesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.kythe.proto.GraphNodeR\x05value:\x028\x01\"v\n" +
	"\n" +
	"NodeFilter\x12-\n" +
	"\x12included_languages\x18\x01 \x03(\tR\x11includedLanguages\x129\n" +
	"\x0eincluded_files\x18\x02 \x03(\v2\x12.kythe.proto.VNameR\rincludedFiles\"#\n" +
	"\aTickets\x12\x18\n" +
	"\atickets\x18\x01 \x03(\tR\atickets\"q\n" +
	"\x14TypeHierarchyRequest\x12\x1f\n" +
	"\vtype_ticket\x18\x01 \x01(\tR\n" +
	"typeTicket\x128\n" +
	"\vnode_filter\x18\x02 \x01(\v2\x17.kythe.proto.NodeFilterR\n" +
	"nodeFilter\"_\n" +
	"\x12TypeHierarchyReply\x12\x1f\n" +
	"\vtype_ticket\x18\x01 \x01(\tR\n" +
	"typeTicket\x12(\n" +
	"\x05graph\x18\x02 \x01(\v2\x12.kythe.proto.GraphR\x05graph\"*\n" +
	"\x0eCallersRequest\x12\x18\n" +
	"\atickets\x18\x01 \x03(\tR\atickets\"8\n" +
	"\fCallersReply\x12(\n" +
	"\x05graph\x18\x01 \x01(\v2\x12.kythe.proto.GraphR\x05graph\"*\n" +
	"\x0eCalleesRequest\x12\x18\n" +
	"\atickets\x18\x01 \x03(\tR\atickets\"8\n" +
	"\fCalleesReply\x12(\n" +
	"\x05graph\x18\x01 \x01(\v2\x12.kythe.proto.GraphR\x05graph\">\n" +
	"\x11ParametersRequest\x12)\n" +
	"\x10function_tickets\x18\x01 \x03(\tR\x0ffunctionTickets\"\xb7\x04\n" +
	"\x0fParametersReply\x12l\n" +
	"\x16function_to_parameters\x18\x01 \x03(\v26.kythe.proto.ParametersReply.FunctionToParametersEntryR\x14functionToParameters\x12p\n" +
	"\x18function_to_return_value\x18\x02 \x03(\v27.kythe.proto.ParametersReply.FunctionToReturnValueEntryR\x15functionToReturnValue\x12G\n" +
	"\tnode_data\x18\x03 \x03(\v2*.kythe.proto.ParametersReply.NodeDataEntryR\bnodeData\x1a]\n" +
	"\x19FunctionToParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.kythe.proto.TicketsR\x05value:\x028\x01\x1aH\n" +
	"\x1aFunctionToReturnValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aR\n" +
	"\rNodeDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.kythe.proto.NodeDataR\x05value:\x028\x01\"*\n" +
	"\x0eParentsRequest\x12\x18\n" +
	"\atickets\x18\x01 \x03(\tR\atickets\"\xc0\x01\n" +
	"\fParentsReply\x12W\n" +
	"\x10input_to_parents\x18\x01 \x03(\v2-.kythe.proto.ParentsReply.InputToParentsEntryR\x0einputToParents\x1aW\n" +
	"\x13InputToParentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.kythe.proto.TicketsR\x05value:\x028\x01\"+\n" +
	"\x0fChildrenRequest\x12\x18\n" +
	"\atickets\x18\x01 \x03(\tR\atickets\"\xc6\x01\n" +
	"\rChildrenReply\x12[\n" +
	"\x11input_to_children\x18\x01 \x03(\v2/.kythe.proto.ChildrenReply.InputToChildrenEntryR\x0finputToChildren\x1aX\n" +
	"\x14InputToChildrenEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.kythe.proto.TicketsR\x05value:\x028\x012\xcc\x03\n" +
	"\x0eExploreService\x12C\n" +
	"\aCallers\x12\x1b.kythe.proto.CallersRequest\x1a\x19.kythe.proto.CallersReply\"\x00\x12C\n" +
	"\aCallees\x12\x1b.kythe.proto.CalleesRequest\x1a\x19.kythe.proto.CalleesReply\"\x00\x12C\n" +
	"\aParents\x12\x1b.kythe.proto.ParentsRequest\x1a\x19.kythe.proto.ParentsReply\"\x00\x12F\n" +
	"\bChildren\x12\x1c.kythe.proto.ChildrenRequest\x1a\x1a.kythe.proto.ChildrenReply\"\x00\x12U\n" +
	"\rTypeHierarchy\x12!.kythe.proto.TypeHierarchyRequest\x1a\x1f.kythe.proto.TypeHierarchyReply\"\x00\x12L\n" +
	"\n" +
	"Parameters\x12\x1e.kythe.proto.ParametersRequest\x1a\x1c.kythe.proto.ParametersReply\"\x00BJ\n" +
	"\x1fcom.google.devtools.kythe.protoP\x01Z%kythe.io/kythe/proto/explore_go_protob\x06proto3"

var (
	file_kythe_proto_explore_proto_rawDescOnce sync.Once
	file_kythe_proto_explore_proto_rawDescData []byte
)

func file_kythe_proto_explore_proto_rawDescGZIP() []byte {
	file_kythe_proto_explore_proto_rawDescOnce.Do(func() {
		file_kythe_proto_explore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kythe_proto_explore_proto_rawDesc), len(file_kythe_proto_explore_proto_rawDesc)))
	})
	return file_kythe_proto_explore_proto_rawDescData
}

var file_kythe_proto_explore_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_kythe_proto_explore_proto_goTypes = []any{
	(*NodeData)(nil),                     // 0: kythe.proto.NodeData
	(*GraphNode)(nil),                    // 1: kythe.proto.GraphNode
	(*Graph)(nil),                        // 2: kythe.proto.Graph
	(*NodeFilter)(nil),                   // 3: kythe.proto.NodeFilter
	(*Tickets)(nil),                      // 4: kythe.proto.Tickets
	(*TypeHierarchyRequest)(nil),         // 5: kythe.proto.TypeHierarchyRequest
	(*TypeHierarchyReply)(nil),           // 6: kythe.proto.TypeHierarchyReply
	(*CallersRequest)(nil),               // 7: kythe.proto.CallersRequest
	(*CallersReply)(nil),                 // 8: kythe.proto.CallersReply
	(*CalleesRequest)(nil),               // 9: kythe.proto.CalleesRequest
	(*CalleesReply)(nil),                 // 10: kythe.proto.CalleesReply
	(*ParametersRequest)(nil),            // 11: kythe.proto.ParametersRequest
	(*ParametersReply)(nil),              // 12: kythe.proto.ParametersReply
	(*ParentsRequest)(nil),               // 13: kythe.proto.ParentsRequest
	(*ParentsReply)(nil),                 // 14: kythe.proto.ParentsReply
	(*ChildrenRequest)(nil),              // 15: kythe.proto.ChildrenRequest
	(*ChildrenReply)(nil),                // 16: kythe.proto.ChildrenReply
	nil,                                  // 17: kythe.proto.Graph.NodesEntry
	nil,                                  // 18: kythe.proto.ParametersReply.FunctionToParametersEntry
	nil,                                  // 19: kythe.proto.ParametersReply.FunctionToReturnValueEntry
	nil,                                  // 20: kythe.proto.ParametersReply.NodeDataEntry
	nil,                                  // 21: kythe.proto.ParentsReply.InputToParentsEntry
	nil,                                  // 22: kythe.proto.ChildrenReply.InputToChildrenEntry
	(*xref_go_proto.Location)(nil),       // 23: kythe.proto.Location
	(*common_go_proto.MarkedSource)(nil), // 24: kythe.proto.common.MarkedSource
	(*storage_go_proto.VName)(nil),       // 25: kythe.proto.VName
}
var file_kythe_proto_explore_proto_depIdxs = []int32{
	23, // 0: kythe.proto.NodeData.locations:type_name -> kythe.proto.Location
	24, // 1: kythe.proto.NodeData.code:type_name -> kythe.proto.common.MarkedSource
	0,  // 2: kythe.proto.GraphNode.node_data:type_name -> kythe.proto.NodeData
	17, // 3: kythe.proto.Graph.nodes:type_name -> kythe.proto.Graph.NodesEntry
	25, // 4: kythe.proto.NodeFilter.included_files:type_name -> kythe.proto.VName
	3,  // 5: kythe.proto.TypeHierarchyRequest.node_filter:type_name -> kythe.proto.NodeFilter
	2,  // 6: kythe.proto.TypeHierarchyReply.graph:type_name -> kythe.proto.Graph
	2,  // 7: kythe.proto.CallersReply.graph:type_name -> kythe.proto.Graph
	2,  // 8: kythe.proto.CalleesReply.graph:type_name -> kythe.proto.Graph
	18, // 9: kythe.proto.ParametersReply.function_to_parameters:type_name -> kythe.proto.ParametersReply.FunctionToParametersEntry
	19, // 10: kythe.proto.ParametersReply.function_to_return_value:type_name -> kythe.proto.ParametersReply.FunctionToReturnValueEntry
	20, // 11: kythe.proto.ParametersReply.node_data:type_name -> kythe.proto.ParametersReply.NodeDataEntry
	21, // 12: kythe.proto.ParentsReply.input_to_parents:type_name -> kythe.proto.ParentsReply.InputToParentsEntry
	22, // 13: kythe.proto.ChildrenReply.input_to_children:type_name -> kythe.proto.ChildrenReply.InputToChildrenEntry
	1,  // 14: kythe.proto.Graph.NodesEntry.value:type_name -> kythe.proto.GraphNode
	4,  // 15: kythe.proto.ParametersReply.FunctionToParametersEntry.value:type_name -> kythe.proto.Tickets
	0,  // 16: kythe.proto.ParametersReply.NodeDataEntry.value:type_name -> kythe.proto.NodeData
	4,  // 17: kythe.proto.ParentsReply.InputToParentsEntry.value:type_name -> kythe.proto.Tickets
	4,  // 18: kythe.proto.ChildrenReply.InputToChildrenEntry.value:type_name -> kythe.proto.Tickets
	7,  // 19: kythe.proto.ExploreService.Callers:input_type -> kythe.proto.CallersRequest
	9,  // 20: kythe.proto.ExploreService.Callees:input_type -> kythe.proto.CalleesRequest
	13, // 21: kythe.proto.ExploreService.Parents:input_type -> kythe.proto.ParentsRequest
	15, // 22: kythe.proto.ExploreService.Children:input_type -> kythe.proto.ChildrenRequest
	5,  // 23: kythe.proto.ExploreService.TypeHierarchy:input_type -> kythe.proto.TypeHierarchyRequest
	11, // 24: kythe.proto.ExploreService.Parameters:input_type -> kythe.proto.ParametersRequest
	8,  // 25: kythe.proto.ExploreService.Callers:output_type -> kythe.proto.CallersReply
	10, // 26: kythe.proto.ExploreService.Callees:output_type -> kythe.proto.CalleesReply
	14, // 27: kythe.proto.ExploreService.Parents:output_type -> kythe.proto.ParentsReply
	16, // 28: kythe.proto.ExploreService.Children:output_type -> kythe.proto.ChildrenReply
	6,  // 29: kythe.proto.ExploreService.TypeHierarchy:output_type -> kythe.proto.TypeHierarchyReply
	12, // 30: kythe.proto.ExploreService.Parameters:output_type -> kythe.proto.ParametersReply
	25, // [25:31] is the sub-list for method output_type
	19, // [19:25] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_kythe_proto_explore_proto_init() }
func file_kythe_proto_explore_proto_init() {
	if File_kythe_proto_explore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kythe_proto_explore_proto_rawDesc), len(file_kythe_proto_explore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kythe_proto_explore_proto_goTypes,
		DependencyIndexes: file_kythe_proto_explore_proto_depIdxs,
		MessageInfos:      file_kythe_proto_explore_proto_msgTypes,
	}.Build()
	File_kythe_proto_explore_proto = out.File
	file_kythe_proto_explore_proto_goTypes = nil
	file_kythe_proto_explore_proto_depIdxs = nil
}
