// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kythe/proto/explore.proto

/*
Package explore_go_proto is a generated protocol buffer package.

It is generated from these files:
	kythe/proto/explore.proto

It has these top-level messages:
	NodeData
	GraphNode
	Graph
	NodeFilter
	Tickets
	TypeHierarchyRequest
	TypeHierarchyReply
	CallersRequest
	CallersReply
	CalleesRequest
	CalleesReply
	ParametersRequest
	ParametersReply
	ContainersRequest
	ContainersReply
	ContentsRequest
	ContentsReply
*/
package explore_go_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import kythe_proto_common "kythe.io/kythe/proto/common_go_proto"
import kythe_proto "kythe.io/kythe/proto/storage_go_proto"
import kythe_proto1 "kythe.io/kythe/proto/xref_go_proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeData struct {
	Kind             string                           `protobuf:"bytes,1,opt,name=kind" json:"kind,omitempty"`
	Subkind          string                           `protobuf:"bytes,2,opt,name=subkind" json:"subkind,omitempty"`
	Locations        []*kythe_proto1.Location         `protobuf:"bytes,3,rep,name=locations" json:"locations,omitempty"`
	DefinitionAnchor string                           `protobuf:"bytes,4,opt,name=definition_anchor,json=definitionAnchor" json:"definition_anchor,omitempty"`
	Code             *kythe_proto_common.MarkedSource `protobuf:"bytes,5,opt,name=code" json:"code,omitempty"`
}

func (m *NodeData) Reset()                    { *m = NodeData{} }
func (m *NodeData) String() string            { return proto.CompactTextString(m) }
func (*NodeData) ProtoMessage()               {}
func (*NodeData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NodeData) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *NodeData) GetSubkind() string {
	if m != nil {
		return m.Subkind
	}
	return ""
}

func (m *NodeData) GetLocations() []*kythe_proto1.Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *NodeData) GetDefinitionAnchor() string {
	if m != nil {
		return m.DefinitionAnchor
	}
	return ""
}

func (m *NodeData) GetCode() *kythe_proto_common.MarkedSource {
	if m != nil {
		return m.Code
	}
	return nil
}

type GraphNode struct {
	NodeData     *NodeData `protobuf:"bytes,1,opt,name=node_data,json=nodeData" json:"node_data,omitempty"`
	Predecessors *Tickets  `protobuf:"bytes,2,opt,name=predecessors" json:"predecessors,omitempty"`
	Successors   *Tickets  `protobuf:"bytes,3,opt,name=successors" json:"successors,omitempty"`
}

func (m *GraphNode) Reset()                    { *m = GraphNode{} }
func (m *GraphNode) String() string            { return proto.CompactTextString(m) }
func (*GraphNode) ProtoMessage()               {}
func (*GraphNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GraphNode) GetNodeData() *NodeData {
	if m != nil {
		return m.NodeData
	}
	return nil
}

func (m *GraphNode) GetPredecessors() *Tickets {
	if m != nil {
		return m.Predecessors
	}
	return nil
}

func (m *GraphNode) GetSuccessors() *Tickets {
	if m != nil {
		return m.Successors
	}
	return nil
}

type Graph struct {
	Nodes map[string]*GraphNode `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Graph) Reset()                    { *m = Graph{} }
func (m *Graph) String() string            { return proto.CompactTextString(m) }
func (*Graph) ProtoMessage()               {}
func (*Graph) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Graph) GetNodes() map[string]*GraphNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type NodeFilter struct {
	IncludedLanguages []string             `protobuf:"bytes,1,rep,name=included_languages,json=includedLanguages" json:"included_languages,omitempty"`
	IncludedFiles     []*kythe_proto.VName `protobuf:"bytes,2,rep,name=included_files,json=includedFiles" json:"included_files,omitempty"`
}

func (m *NodeFilter) Reset()                    { *m = NodeFilter{} }
func (m *NodeFilter) String() string            { return proto.CompactTextString(m) }
func (*NodeFilter) ProtoMessage()               {}
func (*NodeFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NodeFilter) GetIncludedLanguages() []string {
	if m != nil {
		return m.IncludedLanguages
	}
	return nil
}

func (m *NodeFilter) GetIncludedFiles() []*kythe_proto.VName {
	if m != nil {
		return m.IncludedFiles
	}
	return nil
}

type Tickets struct {
	Tickets []string `protobuf:"bytes,1,rep,name=tickets" json:"tickets,omitempty"`
}

func (m *Tickets) Reset()                    { *m = Tickets{} }
func (m *Tickets) String() string            { return proto.CompactTextString(m) }
func (*Tickets) ProtoMessage()               {}
func (*Tickets) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Tickets) GetTickets() []string {
	if m != nil {
		return m.Tickets
	}
	return nil
}

type TypeHierarchyRequest struct {
	TypeTicket string      `protobuf:"bytes,1,opt,name=type_ticket,json=typeTicket" json:"type_ticket,omitempty"`
	NodeFilter *NodeFilter `protobuf:"bytes,2,opt,name=node_filter,json=nodeFilter" json:"node_filter,omitempty"`
}

func (m *TypeHierarchyRequest) Reset()                    { *m = TypeHierarchyRequest{} }
func (m *TypeHierarchyRequest) String() string            { return proto.CompactTextString(m) }
func (*TypeHierarchyRequest) ProtoMessage()               {}
func (*TypeHierarchyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *TypeHierarchyRequest) GetTypeTicket() string {
	if m != nil {
		return m.TypeTicket
	}
	return ""
}

func (m *TypeHierarchyRequest) GetNodeFilter() *NodeFilter {
	if m != nil {
		return m.NodeFilter
	}
	return nil
}

type TypeHierarchyReply struct {
	TypeTicket string `protobuf:"bytes,1,opt,name=type_ticket,json=typeTicket" json:"type_ticket,omitempty"`
	Graph      *Graph `protobuf:"bytes,2,opt,name=graph" json:"graph,omitempty"`
}

func (m *TypeHierarchyReply) Reset()                    { *m = TypeHierarchyReply{} }
func (m *TypeHierarchyReply) String() string            { return proto.CompactTextString(m) }
func (*TypeHierarchyReply) ProtoMessage()               {}
func (*TypeHierarchyReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TypeHierarchyReply) GetTypeTicket() string {
	if m != nil {
		return m.TypeTicket
	}
	return ""
}

func (m *TypeHierarchyReply) GetGraph() *Graph {
	if m != nil {
		return m.Graph
	}
	return nil
}

type CallersRequest struct {
	FunctionTicket string      `protobuf:"bytes,1,opt,name=function_ticket,json=functionTicket" json:"function_ticket,omitempty"`
	NodeFilter     *NodeFilter `protobuf:"bytes,2,opt,name=node_filter,json=nodeFilter" json:"node_filter,omitempty"`
}

func (m *CallersRequest) Reset()                    { *m = CallersRequest{} }
func (m *CallersRequest) String() string            { return proto.CompactTextString(m) }
func (*CallersRequest) ProtoMessage()               {}
func (*CallersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CallersRequest) GetFunctionTicket() string {
	if m != nil {
		return m.FunctionTicket
	}
	return ""
}

func (m *CallersRequest) GetNodeFilter() *NodeFilter {
	if m != nil {
		return m.NodeFilter
	}
	return nil
}

type CallersReply struct {
	FunctionTicket string `protobuf:"bytes,1,opt,name=function_ticket,json=functionTicket" json:"function_ticket,omitempty"`
	Graph          *Graph `protobuf:"bytes,2,opt,name=graph" json:"graph,omitempty"`
}

func (m *CallersReply) Reset()                    { *m = CallersReply{} }
func (m *CallersReply) String() string            { return proto.CompactTextString(m) }
func (*CallersReply) ProtoMessage()               {}
func (*CallersReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CallersReply) GetFunctionTicket() string {
	if m != nil {
		return m.FunctionTicket
	}
	return ""
}

func (m *CallersReply) GetGraph() *Graph {
	if m != nil {
		return m.Graph
	}
	return nil
}

type CalleesRequest struct {
	FunctionTicket string      `protobuf:"bytes,1,opt,name=function_ticket,json=functionTicket" json:"function_ticket,omitempty"`
	NodeFilter     *NodeFilter `protobuf:"bytes,2,opt,name=node_filter,json=nodeFilter" json:"node_filter,omitempty"`
}

func (m *CalleesRequest) Reset()                    { *m = CalleesRequest{} }
func (m *CalleesRequest) String() string            { return proto.CompactTextString(m) }
func (*CalleesRequest) ProtoMessage()               {}
func (*CalleesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CalleesRequest) GetFunctionTicket() string {
	if m != nil {
		return m.FunctionTicket
	}
	return ""
}

func (m *CalleesRequest) GetNodeFilter() *NodeFilter {
	if m != nil {
		return m.NodeFilter
	}
	return nil
}

type CalleesReply struct {
	FunctionTicket string `protobuf:"bytes,1,opt,name=function_ticket,json=functionTicket" json:"function_ticket,omitempty"`
	Graph          *Graph `protobuf:"bytes,2,opt,name=graph" json:"graph,omitempty"`
}

func (m *CalleesReply) Reset()                    { *m = CalleesReply{} }
func (m *CalleesReply) String() string            { return proto.CompactTextString(m) }
func (*CalleesReply) ProtoMessage()               {}
func (*CalleesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *CalleesReply) GetFunctionTicket() string {
	if m != nil {
		return m.FunctionTicket
	}
	return ""
}

func (m *CalleesReply) GetGraph() *Graph {
	if m != nil {
		return m.Graph
	}
	return nil
}

type ParametersRequest struct {
	FunctionTickets []string `protobuf:"bytes,1,rep,name=function_tickets,json=functionTickets" json:"function_tickets,omitempty"`
}

func (m *ParametersRequest) Reset()                    { *m = ParametersRequest{} }
func (m *ParametersRequest) String() string            { return proto.CompactTextString(m) }
func (*ParametersRequest) ProtoMessage()               {}
func (*ParametersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ParametersRequest) GetFunctionTickets() []string {
	if m != nil {
		return m.FunctionTickets
	}
	return nil
}

type ParametersReply struct {
	FunctionToParameters  map[string]*Tickets  `protobuf:"bytes,1,rep,name=function_to_parameters,json=functionToParameters" json:"function_to_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FunctionToReturnValue map[string]string    `protobuf:"bytes,2,rep,name=function_to_return_value,json=functionToReturnValue" json:"function_to_return_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NodeData              map[string]*NodeData `protobuf:"bytes,3,rep,name=node_data,json=nodeData" json:"node_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ParametersReply) Reset()                    { *m = ParametersReply{} }
func (m *ParametersReply) String() string            { return proto.CompactTextString(m) }
func (*ParametersReply) ProtoMessage()               {}
func (*ParametersReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ParametersReply) GetFunctionToParameters() map[string]*Tickets {
	if m != nil {
		return m.FunctionToParameters
	}
	return nil
}

func (m *ParametersReply) GetFunctionToReturnValue() map[string]string {
	if m != nil {
		return m.FunctionToReturnValue
	}
	return nil
}

func (m *ParametersReply) GetNodeData() map[string]*NodeData {
	if m != nil {
		return m.NodeData
	}
	return nil
}

type ContainersRequest struct {
	Ticket []string `protobuf:"bytes,1,rep,name=ticket" json:"ticket,omitempty"`
}

func (m *ContainersRequest) Reset()                    { *m = ContainersRequest{} }
func (m *ContainersRequest) String() string            { return proto.CompactTextString(m) }
func (*ContainersRequest) ProtoMessage()               {}
func (*ContainersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ContainersRequest) GetTicket() []string {
	if m != nil {
		return m.Ticket
	}
	return nil
}

type ContainersReply struct {
	InputToContainers map[string]*Tickets  `protobuf:"bytes,1,rep,name=input_to_containers,json=inputToContainers" json:"input_to_containers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NodeData          map[string]*NodeData `protobuf:"bytes,2,rep,name=node_data,json=nodeData" json:"node_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ContainersReply) Reset()                    { *m = ContainersReply{} }
func (m *ContainersReply) String() string            { return proto.CompactTextString(m) }
func (*ContainersReply) ProtoMessage()               {}
func (*ContainersReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ContainersReply) GetInputToContainers() map[string]*Tickets {
	if m != nil {
		return m.InputToContainers
	}
	return nil
}

func (m *ContainersReply) GetNodeData() map[string]*NodeData {
	if m != nil {
		return m.NodeData
	}
	return nil
}

type ContentsRequest struct {
	Ticket     []string    `protobuf:"bytes,1,rep,name=ticket" json:"ticket,omitempty"`
	NodeFilter *NodeFilter `protobuf:"bytes,2,opt,name=node_filter,json=nodeFilter" json:"node_filter,omitempty"`
}

func (m *ContentsRequest) Reset()                    { *m = ContentsRequest{} }
func (m *ContentsRequest) String() string            { return proto.CompactTextString(m) }
func (*ContentsRequest) ProtoMessage()               {}
func (*ContentsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ContentsRequest) GetTicket() []string {
	if m != nil {
		return m.Ticket
	}
	return nil
}

func (m *ContentsRequest) GetNodeFilter() *NodeFilter {
	if m != nil {
		return m.NodeFilter
	}
	return nil
}

type ContentsReply struct {
	InputToContents map[string]*Tickets  `protobuf:"bytes,1,rep,name=input_to_contents,json=inputToContents" json:"input_to_contents,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NodeData        map[string]*NodeData `protobuf:"bytes,2,rep,name=node_data,json=nodeData" json:"node_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ContentsReply) Reset()                    { *m = ContentsReply{} }
func (m *ContentsReply) String() string            { return proto.CompactTextString(m) }
func (*ContentsReply) ProtoMessage()               {}
func (*ContentsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ContentsReply) GetInputToContents() map[string]*Tickets {
	if m != nil {
		return m.InputToContents
	}
	return nil
}

func (m *ContentsReply) GetNodeData() map[string]*NodeData {
	if m != nil {
		return m.NodeData
	}
	return nil
}

func init() {
	proto.RegisterType((*NodeData)(nil), "kythe.proto.NodeData")
	proto.RegisterType((*GraphNode)(nil), "kythe.proto.GraphNode")
	proto.RegisterType((*Graph)(nil), "kythe.proto.Graph")
	proto.RegisterType((*NodeFilter)(nil), "kythe.proto.NodeFilter")
	proto.RegisterType((*Tickets)(nil), "kythe.proto.Tickets")
	proto.RegisterType((*TypeHierarchyRequest)(nil), "kythe.proto.TypeHierarchyRequest")
	proto.RegisterType((*TypeHierarchyReply)(nil), "kythe.proto.TypeHierarchyReply")
	proto.RegisterType((*CallersRequest)(nil), "kythe.proto.CallersRequest")
	proto.RegisterType((*CallersReply)(nil), "kythe.proto.CallersReply")
	proto.RegisterType((*CalleesRequest)(nil), "kythe.proto.CalleesRequest")
	proto.RegisterType((*CalleesReply)(nil), "kythe.proto.CalleesReply")
	proto.RegisterType((*ParametersRequest)(nil), "kythe.proto.ParametersRequest")
	proto.RegisterType((*ParametersReply)(nil), "kythe.proto.ParametersReply")
	proto.RegisterType((*ContainersRequest)(nil), "kythe.proto.ContainersRequest")
	proto.RegisterType((*ContainersReply)(nil), "kythe.proto.ContainersReply")
	proto.RegisterType((*ContentsRequest)(nil), "kythe.proto.ContentsRequest")
	proto.RegisterType((*ContentsReply)(nil), "kythe.proto.ContentsReply")
}

func init() { proto.RegisterFile("kythe/proto/explore.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 993 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0x8e, 0xe3, 0xb8, 0x89, 0x8f, 0x9b, 0x38, 0x1e, 0x5c, 0xe3, 0x98, 0xd2, 0x84, 0xed, 0x05,
	0xa6, 0x01, 0x47, 0x72, 0x2a, 0x08, 0x5c, 0x20, 0x41, 0x48, 0x5a, 0xa4, 0x50, 0x45, 0xdb, 0x50,
	0x21, 0x10, 0xb2, 0xa6, 0xbb, 0xc7, 0xce, 0xca, 0xeb, 0x9d, 0xed, 0xec, 0x6c, 0x54, 0xbf, 0x04,
	0xaf, 0xc2, 0x25, 0xaf, 0xc1, 0x0d, 0x0f, 0xc0, 0x13, 0xf0, 0x0a, 0x68, 0x66, 0x76, 0xd7, 0x3b,
	0xf6, 0xda, 0x2d, 0x2a, 0x15, 0xdc, 0xcd, 0x9c, 0x9f, 0xef, 0x3b, 0x7f, 0x7b, 0x76, 0x60, 0x6f,
	0x3c, 0x15, 0xd7, 0x78, 0x14, 0x72, 0x26, 0xd8, 0x11, 0xbe, 0x0c, 0x7d, 0xc6, 0xb1, 0xa7, 0x6e,
	0xa4, 0xa6, 0x54, 0xfa, 0xd2, 0x69, 0xe7, 0xed, 0x1c, 0x36, 0x99, 0xb0, 0x20, 0xd1, 0x18, 0x08,
	0x91, 0x60, 0x9c, 0x8e, 0x52, 0xa7, 0x56, 0x5e, 0xf5, 0x92, 0xe3, 0x50, 0xcb, 0xad, 0xdf, 0x4b,
	0xb0, 0xf5, 0x84, 0xb9, 0xf8, 0x0d, 0x15, 0x94, 0x10, 0xd8, 0x18, 0x7b, 0x81, 0xdb, 0x2e, 0x1d,
	0x94, 0xba, 0x55, 0x5b, 0x9d, 0x49, 0x1b, 0x36, 0xa3, 0xf8, 0xb9, 0x12, 0xaf, 0x2b, 0x71, 0x7a,
	0x25, 0xc7, 0x50, 0xf5, 0x99, 0x43, 0x85, 0xc7, 0x82, 0xa8, 0x5d, 0x3e, 0x28, 0x77, 0x6b, 0xfd,
	0x3b, 0xbd, 0x5c, 0xa0, 0xbd, 0x8b, 0x44, 0x6b, 0xcf, 0xec, 0xc8, 0x21, 0x34, 0x5c, 0x1c, 0x7a,
	0x81, 0x27, 0xaf, 0x03, 0x1a, 0x38, 0xd7, 0x8c, 0xb7, 0x37, 0x14, 0xf0, 0xee, 0x4c, 0xf1, 0x95,
	0x92, 0x93, 0x87, 0xb0, 0xe1, 0x30, 0x17, 0xdb, 0x95, 0x83, 0x52, 0xb7, 0xd6, 0x3f, 0x30, 0xc0,
	0x93, 0xc4, 0xbf, 0xa3, 0x7c, 0x8c, 0xee, 0x53, 0x16, 0x73, 0x07, 0x6d, 0x65, 0x6d, 0xfd, 0x5a,
	0x82, 0xea, 0x23, 0x4e, 0xc3, 0x6b, 0x99, 0x17, 0xe9, 0x43, 0x35, 0x60, 0x2e, 0x0e, 0x5c, 0x2a,
	0xa8, 0x4a, 0x6c, 0x3e, 0xca, 0x34, 0x7b, 0x7b, 0x2b, 0x48, 0xeb, 0x70, 0x02, 0xb7, 0x43, 0x8e,
	0x2e, 0x3a, 0x18, 0x45, 0x8c, 0x47, 0x2a, 0xf1, 0x5a, 0xbf, 0x69, 0xb8, 0x5d, 0x79, 0xce, 0x18,
	0x45, 0x64, 0x1b, 0x96, 0xe4, 0x21, 0x40, 0x14, 0x3b, 0xa9, 0x5f, 0x79, 0x85, 0x5f, 0xce, 0xce,
	0xfa, 0xa5, 0x04, 0x15, 0x15, 0x31, 0x39, 0x86, 0x8a, 0x8c, 0x22, 0x6a, 0x97, 0x54, 0x3d, 0xdf,
	0x37, 0x5c, 0x95, 0x89, 0x8a, 0x37, 0x3a, 0x0b, 0x04, 0x9f, 0xda, 0xda, 0xb6, 0x73, 0x09, 0x30,
	0x13, 0x92, 0x5d, 0x28, 0x8f, 0x71, 0x9a, 0xf4, 0x50, 0x1e, 0xc9, 0xc7, 0x50, 0xb9, 0xa1, 0x7e,
	0x8c, 0x49, 0x1e, 0xad, 0x45, 0x50, 0xe9, 0x6e, 0x6b, 0xa3, 0x2f, 0xd6, 0x4f, 0x4a, 0xd6, 0x8d,
	0x46, 0x3c, 0xf7, 0x7c, 0x81, 0x9c, 0x7c, 0x02, 0xc4, 0x0b, 0x1c, 0x3f, 0x76, 0xd1, 0x1d, 0xf8,
	0x34, 0x18, 0xc5, 0x74, 0x94, 0x44, 0x58, 0xb5, 0x1b, 0xa9, 0xe6, 0x22, 0x55, 0x90, 0xcf, 0x61,
	0x27, 0x33, 0x1f, 0x7a, 0x3e, 0xca, 0xfa, 0xc9, 0x64, 0x88, 0xc1, 0xfb, 0xec, 0x09, 0x9d, 0xa0,
	0xbd, 0x9d, 0x5a, 0x9e, 0x4b, 0x43, 0xeb, 0x3e, 0x6c, 0x26, 0xf5, 0x91, 0x73, 0x27, 0xf4, 0x31,
	0x61, 0x4a, 0xaf, 0xd6, 0x0b, 0x68, 0x5e, 0x4d, 0x43, 0x7c, 0xec, 0x21, 0xa7, 0xdc, 0xb9, 0x9e,
	0xda, 0xf8, 0x22, 0xc6, 0x48, 0x90, 0x7d, 0xa8, 0x89, 0x69, 0x88, 0x03, 0x6d, 0x97, 0x14, 0x00,
	0xa4, 0x48, 0x63, 0x92, 0x13, 0xa8, 0xa9, 0x51, 0x18, 0xaa, 0xb4, 0x92, 0x6a, 0xbc, 0xbb, 0x30,
	0x0c, 0x3a, 0x6b, 0x1b, 0x82, 0xec, 0x6c, 0x0d, 0x80, 0xcc, 0x51, 0x86, 0xfe, 0xf4, 0xd5, 0x84,
	0x5d, 0xa8, 0x8c, 0x64, 0x79, 0x13, 0x2a, 0xb2, 0x58, 0x78, 0x5b, 0x1b, 0x58, 0x11, 0xec, 0x9c,
	0x52, 0xdf, 0x47, 0x1e, 0xa5, 0xd9, 0x7c, 0x08, 0xf5, 0x61, 0x1c, 0x38, 0xea, 0x33, 0x31, 0x08,
	0x76, 0x52, 0xf1, 0x1b, 0x67, 0x45, 0xe1, 0x76, 0x46, 0x2a, 0xf3, 0x79, 0x6d, 0xca, 0x7f, 0x9e,
	0x17, 0xfe, 0x17, 0x79, 0xe1, 0xdb, 0xcb, 0xeb, 0x4b, 0x68, 0x5c, 0x52, 0x4e, 0x27, 0x28, 0x72,
	0x2d, 0xfb, 0x08, 0x76, 0xe7, 0x78, 0xd2, 0xd9, 0xad, 0x9b, 0x44, 0x91, 0xf5, 0xdb, 0x06, 0xd4,
	0xf3, 0x00, 0x32, 0x4c, 0x1f, 0x5a, 0x33, 0x77, 0x36, 0x08, 0x33, 0x75, 0xb2, 0x0c, 0x3e, 0x35,
	0xc2, 0x99, 0xf3, 0xee, 0x9d, 0xa7, 0x0c, 0x6c, 0xa6, 0xd1, 0x5b, 0xa2, 0x39, 0x2c, 0x50, 0x91,
	0x10, 0xda, 0x79, 0x36, 0x8e, 0x22, 0xe6, 0xc1, 0x20, 0xdd, 0x13, 0x92, 0xef, 0xb3, 0xd7, 0xe4,
	0xb3, 0x95, 0xeb, 0x33, 0xe9, 0xa9, 0x09, 0xef, 0x0c, 0x8b, 0x74, 0xe4, 0x51, 0x7e, 0x13, 0xeb,
	0xff, 0xc5, 0x83, 0x95, 0x14, 0xe9, 0x66, 0xd6, 0xa8, 0xd9, 0x7a, 0xee, 0xfc, 0x0c, 0x7b, 0x4b,
	0xb3, 0x2d, 0x58, 0x7f, 0x0f, 0xcc, 0xf5, 0x57, 0xbc, 0x8e, 0x67, 0xcb, 0xaf, 0xf3, 0x18, 0x3a,
	0xcb, 0x93, 0x2b, 0xc0, 0x6f, 0xe6, 0xf1, 0xab, 0x79, 0x24, 0x1b, 0xb6, 0x8d, 0x1c, 0x0a, 0x9c,
	0x0f, 0xcd, 0xe0, 0x96, 0xfc, 0x9a, 0x72, 0xab, 0xf9, 0x10, 0x1a, 0xa7, 0x2c, 0x10, 0xd4, 0x0b,
	0x72, 0x93, 0xd7, 0x82, 0x5b, 0xd9, 0x60, 0xcb, 0x79, 0x4b, 0x6e, 0xd6, 0x5f, 0xeb, 0x50, 0xcf,
	0x5b, 0xcb, 0x31, 0x73, 0xe0, 0x1d, 0x2f, 0x08, 0x63, 0x21, 0xbb, 0xee, 0x64, 0xba, 0x64, 0xc6,
	0x8e, 0x0d, 0xfe, 0x39, 0xd7, 0xde, 0xb7, 0xd2, 0xef, 0x8a, 0xcd, 0xc4, 0xba, 0x33, 0x0d, 0x6f,
	0x5e, 0x6e, 0xf6, 0x7a, 0xbd, 0xa0, 0xd7, 0xf3, 0xd0, 0xcb, 0x7a, 0xfd, 0x23, 0xb4, 0x8a, 0x59,
	0xff, 0x85, 0x46, 0xbf, 0x8d, 0xf6, 0x38, 0xba, 0xe0, 0x18, 0x88, 0x57, 0x35, 0xe7, 0x0d, 0x16,
	0xdc, 0x9f, 0xeb, 0xb0, 0x3d, 0x63, 0x91, 0x4d, 0xfd, 0x09, 0x1a, 0x46, 0x53, 0xa5, 0x26, 0x69,
	0xe9, 0xd1, 0x42, 0xdd, 0x33, 0xb7, 0x7c, 0x43, 0xa5, 0x50, 0x17, 0xbf, 0xee, 0x99, 0x52, 0x72,
	0xb6, 0xd8, 0xcc, 0xee, 0x0a, 0xd0, 0x65, 0xad, 0xfc, 0x01, 0x9a, 0x45, 0x7c, 0xff, 0xcf, 0x46,
	0xf6, 0xff, 0x28, 0xc3, 0xce, 0x99, 0x7e, 0x84, 0x3f, 0x45, 0x7e, 0xe3, 0x39, 0x48, 0xbe, 0x87,
	0x6d, 0xe3, 0x15, 0x40, 0x3e, 0x30, 0x03, 0x2b, 0x78, 0x94, 0x74, 0xf6, 0x57, 0x99, 0x84, 0xfe,
	0xd4, 0x5a, 0x23, 0xa7, 0xb0, 0x99, 0xfc, 0x86, 0xc9, 0x7b, 0x66, 0x59, 0x8d, 0x17, 0x41, 0x67,
	0xaf, 0x58, 0x69, 0x82, 0x60, 0x21, 0x08, 0xae, 0x02, 0xc1, 0x0c, 0xe4, 0x02, 0x20, 0xf7, 0x87,
	0xb8, 0xb7, 0x74, 0x39, 0x6b, 0xa8, 0xbb, 0xab, 0x96, 0xb7, 0x46, 0xcb, 0x6d, 0x84, 0x7b, 0x4b,
	0x3f, 0xff, 0x22, 0xb4, 0xb9, 0xf5, 0x60, 0xad, 0x91, 0x73, 0xd8, 0xca, 0x06, 0xf2, 0xee, 0x92,
	0xe9, 0xd3, 0x48, 0x9d, 0xe5, 0xb3, 0x69, 0xad, 0x7d, 0x7d, 0x1f, 0xf6, 0x1d, 0x36, 0xe9, 0x8d,
	0x18, 0x1b, 0xf9, 0xd8, 0x73, 0xf1, 0x46, 0x30, 0xe6, 0x47, 0x79, 0x97, 0xcb, 0xd2, 0xf3, 0x5b,
	0xea, 0x70, 0xfc, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8b, 0xa2, 0x7b, 0x97, 0x93, 0x0d, 0x00,
	0x00,
}
