def generated_llvm_build_targets(ctx):
    ctx.group(ctx, name = "Miscellaneous", parent = "$ROOT")
    ctx.group(ctx, name = "Bindings", parent = "$ROOT")
    ctx.group(ctx, name = "Docs", parent = "$ROOT")
    ctx.group(ctx, name = "Examples", parent = "$ROOT")
    ctx.group(ctx, parent = "$ROOT", name = "Libraries")
    ctx.library(ctx, name = "Analysis", parent = "Libraries", required_libraries = ["BinaryFormat", "Core", "Object", "ProfileData", "Support"])
    ctx.library(ctx, name = "AsmParser", parent = "Libraries", required_libraries = ["BinaryFormat", "Core", "Support"])
    ctx.group(ctx, name = "Bitcode", parent = "Libraries")
    ctx.library(ctx, required_libraries = ["BitstreamReader", "Core", "Support"], name = "BitReader", parent = "Bitcode")
    ctx.library(ctx, name = "BitWriter", parent = "Bitcode", required_libraries = ["Analysis", "Core", "MC", "Object", "Support"])
    ctx.group(ctx, name = "Bitstream", parent = "Libraries")
    ctx.library(ctx, name = "BitstreamReader", parent = "Bitstream", required_libraries = ["Support"])
    ctx.library(ctx, name = "CodeGen", parent = "Libraries", required_libraries = ["Analysis", "BitReader", "BitWriter", "Core", "MC", "ProfileData", "Scalar", "Support", "Target", "TransformUtils"])
    ctx.library(ctx, parent = "Libraries", required_libraries = ["Analysis", "BinaryFormat", "CodeGen", "Core", "DebugInfoCodeView", "DebugInfoDWARF", "DebugInfoMSF", "MC", "MCParser", "Remarks", "Support", "Target"], name = "AsmPrinter")
    ctx.library(ctx, parent = "CodeGen", required_libraries = ["Analysis", "CodeGen", "Core", "MC", "Support", "Target", "TransformUtils"], name = "SelectionDAG")
    ctx.library(ctx, name = "MIRParser", parent = "CodeGen", required_libraries = ["AsmParser", "BinaryFormat", "CodeGen", "Core", "MC", "Support", "Target"])
    ctx.library(ctx, name = "GlobalISel", parent = "CodeGen", required_libraries = ["Analysis", "CodeGen", "Core", "MC", "SelectionDAG", "Support", "Target", "TransformUtils"])
    ctx.group(ctx, name = "DebugInfo", parent = "$ROOT")
    ctx.library(ctx, name = "DebugInfoDWARF", parent = "DebugInfo", required_libraries = ["BinaryFormat", "Object", "MC", "Support"])
    ctx.library(ctx, name = "DebugInfoGSYM", parent = "DebugInfo", required_libraries = ["MC", "Support"])
    ctx.library(ctx, required_libraries = ["Support"], name = "DebugInfoMSF", parent = "DebugInfo")
    ctx.library(ctx, required_libraries = ["Support", "DebugInfoMSF"], name = "DebugInfoCodeView", parent = "DebugInfo")
    ctx.library(ctx, parent = "DebugInfo", required_libraries = ["Object", "Support", "DebugInfoCodeView", "DebugInfoMSF"], name = "DebugInfoPDB")
    ctx.library(ctx, name = "Symbolize", parent = "DebugInfo", required_libraries = ["DebugInfoDWARF", "DebugInfoPDB", "Object", "Support", "Demangle"])
    ctx.library(ctx, parent = "Libraries", name = "Demangle")
    ctx.library(ctx, name = "ExecutionEngine", parent = "Libraries", required_libraries = ["Core", "MC", "Object", "RuntimeDyld", "Support", "Target"])
    ctx.library(ctx, name = "Interpreter", parent = "ExecutionEngine", required_libraries = ["CodeGen", "Core", "ExecutionEngine", "Support"])
    ctx.library(ctx, required_libraries = ["Core", "ExecutionEngine", "Object", "RuntimeDyld", "Support", "Target"], name = "MCJIT", parent = "ExecutionEngine")
    ctx.library(ctx, name = "JITLink", parent = "ExecutionEngine", required_libraries = ["BinaryFormat", "Object", "Support"])
    ctx.library(ctx, name = "RuntimeDyld", parent = "ExecutionEngine", required_libraries = ["MC", "Object", "Support"])
    ctx.optional_library(ctx, parent = "ExecutionEngine", required_libraries = ["CodeGen", "Core", "DebugInfoDWARF", "Support", "Object", "ExecutionEngine"], name = "IntelJITEvents")
    ctx.optional_library(ctx, name = "OProfileJIT", parent = "ExecutionEngine", required_libraries = ["DebugInfoDWARF", "Support", "Object", "ExecutionEngine"])
    ctx.library(ctx, name = "OrcJIT", parent = "ExecutionEngine", required_libraries = ["Core", "ExecutionEngine", "JITLink", "Object", "OrcError", "MC", "Passes", "RuntimeDyld", "Support", "Target", "TransformUtils"])
    ctx.library(ctx, name = "OrcError", parent = "ExecutionEngine", required_libraries = ["Support"])
    ctx.optional_library(ctx, name = "PerfJITEvents", parent = "ExecutionEngine", required_libraries = ["CodeGen", "Core", "DebugInfoDWARF", "ExecutionEngine", "Object", "Support"])
    ctx.library(ctx, name = "FuzzMutate", parent = "Libraries", required_libraries = ["Analysis", "BitReader", "BitWriter", "Core", "Scalar", "Support", "Target"])
    ctx.library(ctx, name = "LineEditor", parent = "Libraries", required_libraries = ["Support"])
    ctx.library(ctx, name = "Linker", parent = "Libraries", required_libraries = ["Core", "Support", "TransformUtils"])
    ctx.library(ctx, name = "Core", parent = "Libraries", required_libraries = ["BinaryFormat", "Remarks", "Support"])
    ctx.library(ctx, required_libraries = ["AsmParser", "BitReader", "Core", "Support"], name = "IRReader", parent = "Libraries")
    ctx.library(ctx, name = "LTO", parent = "Libraries", required_libraries = ["AggressiveInstCombine", "Analysis", "BitReader", "BitWriter", "CodeGen", "Core", "IPO", "InstCombine", "Linker", "MC", "ObjCARC", "Object", "Passes", "Remarks", "Scalar", "Support", "Target", "TransformUtils"])
    ctx.library(ctx, name = "MC", parent = "Libraries", required_libraries = ["Support", "BinaryFormat", "DebugInfoCodeView"])
    ctx.library(ctx, parent = "MC", required_libraries = ["MC", "Support"], name = "MCDisassembler")
    ctx.library(ctx, name = "MCParser", parent = "MC", required_libraries = ["MC", "Support"])
    ctx.library(ctx, required_libraries = ["MC", "Support"], name = "MCA", parent = "Libraries")
    ctx.library(ctx, parent = "Libraries", required_libraries = ["BitReader", "Core", "MC", "BinaryFormat", "MCParser", "Support", "TextAPI"], name = "Object")
    ctx.library(ctx, name = "BinaryFormat", parent = "Libraries", required_libraries = ["Support"])
    ctx.library(ctx, parent = "Libraries", required_libraries = ["Object", "Support", "DebugInfoCodeView", "MC"], name = "ObjectYAML")
    ctx.library(ctx, name = "Option", parent = "Libraries", required_libraries = ["Support"])
    ctx.library(ctx, required_libraries = ["BitstreamReader", "Support"], name = "Remarks", parent = "Libraries")
    ctx.library(ctx, required_libraries = ["AggressiveInstCombine", "Analysis", "CodeGen", "Core", "IPO", "InstCombine", "Scalar", "Support", "Target", "TransformUtils", "Vectorize", "Instrumentation"], name = "Passes", parent = "Libraries")
    ctx.library(ctx, name = "ProfileData", parent = "Libraries", required_libraries = ["Core", "Support"])
    ctx.library(ctx, name = "Coverage", parent = "ProfileData", required_libraries = ["Core", "Object", "ProfileData", "Support"])
    ctx.library(ctx, parent = "Libraries", required_libraries = ["Demangle"], name = "Support")
    ctx.library(ctx, name = "TableGen", parent = "Libraries", required_libraries = ["Support"])
    ctx.library(ctx, required_libraries = ["Support", "BinaryFormat"], name = "TextAPI", parent = "Libraries")
    ctx.library_group(ctx, parent = "Libraries", name = "Engine")
    ctx.library_group(ctx, name = "Native", parent = "Libraries")
    ctx.library_group(ctx, parent = "Libraries", name = "NativeCodeGen")
    ctx.library(ctx, name = "Target", parent = "Libraries", required_libraries = ["Analysis", "Core", "MC", "Support"])
    ctx.library_group(ctx, name = "all-targets", parent = "Libraries")
    ctx.target_group(ctx, name = "AMDGPU", parent = "Target")
    ctx.library(ctx, parent = "AMDGPU", required_libraries = ["Analysis", "AsmPrinter", "CodeGen", "Core", "IPO", "MC", "AMDGPUDesc", "AMDGPUInfo", "AMDGPUUtils", "Scalar", "SelectionDAG", "Support", "Target", "TransformUtils", "Vectorize", "GlobalISel", "BinaryFormat", "MIRParser"], add_to_library_groups = ["AMDGPU"], name = "AMDGPUCodeGen")
    ctx.library(ctx, add_to_library_groups = ["AMDGPU"], name = "AMDGPUAsmParser", parent = "AMDGPU", required_libraries = ["MC", "MCParser", "AMDGPUDesc", "AMDGPUInfo", "AMDGPUUtils", "Support"])
    ctx.library(ctx, required_libraries = ["AMDGPUDesc", "AMDGPUInfo", "AMDGPUUtils", "MC", "MCDisassembler", "Support"], add_to_library_groups = ["AMDGPU"], name = "AMDGPUDisassembler", parent = "AMDGPU")
    ctx.library(ctx, required_libraries = ["Core", "MC", "AMDGPUInfo", "AMDGPUUtils", "Support", "BinaryFormat"], add_to_library_groups = ["AMDGPU"], name = "AMDGPUDesc", parent = "AMDGPU")
    ctx.library(ctx, name = "AMDGPUInfo", parent = "AMDGPU", required_libraries = ["Support"], add_to_library_groups = ["AMDGPU"])
    ctx.library(ctx, name = "AMDGPUUtils", parent = "AMDGPU", required_libraries = ["Core", "MC", "BinaryFormat", "Support"], add_to_library_groups = ["AMDGPU"])
    ctx.target_group(ctx, name = "ARC", parent = "Target")
    ctx.library(ctx, name = "ARCCodeGen", parent = "ARC", required_libraries = ["Analysis", "AsmPrinter", "CodeGen", "Core", "MC", "SelectionDAG", "Support", "Target", "TransformUtils", "ARCDesc", "ARCInfo"], add_to_library_groups = ["ARC"])
    ctx.library(ctx, add_to_library_groups = ["ARC"], name = "ARCDisassembler", parent = "ARC", required_libraries = ["MCDisassembler", "Support", "ARCInfo"])
    ctx.library(ctx, name = "ARCDesc", parent = "ARC", required_libraries = ["MC", "Support", "ARCInfo"], add_to_library_groups = ["ARC"])
    ctx.library(ctx, name = "ARCInfo", parent = "ARC", required_libraries = ["Support"], add_to_library_groups = ["ARC"])
    ctx.target_group(ctx, name = "ARM", parent = "Target")
    ctx.library(ctx, parent = "ARM", required_libraries = ["ARMDesc", "ARMInfo", "Analysis", "AsmPrinter", "CodeGen", "Core", "MC", "Scalar", "SelectionDAG", "Support", "Target", "GlobalISel", "ARMUtils", "TransformUtils", "CFGuard"], add_to_library_groups = ["ARM"], name = "ARMCodeGen")
    ctx.library(ctx, add_to_library_groups = ["ARM"], name = "ARMAsmParser", parent = "ARM", required_libraries = ["ARMDesc", "ARMInfo", "MC", "MCParser", "Support", "ARMUtils"])
    ctx.library(ctx, name = "ARMDisassembler", parent = "ARM", required_libraries = ["ARMDesc", "ARMInfo", "MCDisassembler", "Support", "ARMUtils"], add_to_library_groups = ["ARM"])
    ctx.library(ctx, parent = "ARM", required_libraries = ["ARMInfo", "ARMUtils", "MC", "MCDisassembler", "Support"], add_to_library_groups = ["ARM"], name = "ARMDesc")
    ctx.library(ctx, name = "ARMInfo", parent = "ARM", required_libraries = ["Support"], add_to_library_groups = ["ARM"])
    ctx.library(ctx, name = "ARMUtils", parent = "ARM", required_libraries = ["Support"], add_to_library_groups = ["ARM"])
    ctx.target_group(ctx, name = "AArch64", parent = "Target")
    ctx.library(ctx, add_to_library_groups = ["AArch64"], name = "AArch64CodeGen", parent = "AArch64", required_libraries = ["AArch64Desc", "AArch64Info", "AArch64Utils", "Analysis", "AsmPrinter", "CodeGen", "Core", "MC", "Scalar", "SelectionDAG", "Support", "Target", "TransformUtils", "GlobalISel", "CFGuard"])
    ctx.library(ctx, add_to_library_groups = ["AArch64"], name = "AArch64AsmParser", parent = "AArch64", required_libraries = ["AArch64Desc", "AArch64Info", "AArch64Utils", "MC", "MCParser", "Support"])
    ctx.library(ctx, required_libraries = ["AArch64Desc", "AArch64Info", "AArch64Utils", "MC", "MCDisassembler", "Support"], add_to_library_groups = ["AArch64"], name = "AArch64Disassembler", parent = "AArch64")
    ctx.library(ctx, name = "AArch64Desc", parent = "AArch64", required_libraries = ["AArch64Info", "AArch64Utils", "MC", "Support"], add_to_library_groups = ["AArch64"])
    ctx.library(ctx, add_to_library_groups = ["AArch64"], name = "AArch64Info", parent = "AArch64", required_libraries = ["Support"])
    ctx.library(ctx, name = "AArch64Utils", parent = "AArch64", required_libraries = ["Support"], add_to_library_groups = ["AArch64"])
    ctx.target_group(ctx, name = "AVR", parent = "Target")
    ctx.library(ctx, required_libraries = ["AsmPrinter", "CodeGen", "Core", "MC", "AVRDesc", "AVRInfo", "SelectionDAG", "Support", "Target"], add_to_library_groups = ["AVR"], name = "AVRCodeGen", parent = "AVR")
    ctx.library(ctx, required_libraries = ["MC", "MCParser", "AVRDesc", "AVRInfo", "Support"], add_to_library_groups = ["AVR"], name = "AVRAsmParser", parent = "AVR")
    ctx.library(ctx, required_libraries = ["MCDisassembler", "AVRInfo", "Support"], add_to_library_groups = ["AVR"], name = "AVRDisassembler", parent = "AVR")
    ctx.library(ctx, name = "AVRDesc", parent = "AVR", required_libraries = ["MC", "AVRInfo", "Support"], add_to_library_groups = ["AVR"])
    ctx.library(ctx, name = "AVRInfo", parent = "AVR", required_libraries = ["Support"], add_to_library_groups = ["AVR"])
    ctx.target_group(ctx, parent = "Target", name = "BPF")
    ctx.library(ctx, required_libraries = ["AsmPrinter", "CodeGen", "Core", "MC", "BPFDesc", "BPFInfo", "SelectionDAG", "Support", "Target"], add_to_library_groups = ["BPF"], name = "BPFCodeGen", parent = "BPF")
    ctx.library(ctx, required_libraries = ["MC", "MCParser", "BPFDesc", "BPFInfo", "Support"], add_to_library_groups = ["BPF"], name = "BPFAsmParser", parent = "BPF")
    ctx.library(ctx, name = "BPFDisassembler", parent = "BPF", required_libraries = ["MCDisassembler", "BPFInfo", "Support"], add_to_library_groups = ["BPF"])
    ctx.library(ctx, parent = "BPF", required_libraries = ["MC", "BPFInfo", "Support"], add_to_library_groups = ["BPF"], name = "BPFDesc")
    ctx.library(ctx, name = "BPFInfo", parent = "BPF", required_libraries = ["Support"], add_to_library_groups = ["BPF"])
    ctx.library(ctx, parent = "Lanai", required_libraries = ["Analysis", "AsmPrinter", "CodeGen", "Core", "LanaiAsmParser", "LanaiDesc", "LanaiInfo", "MC", "SelectionDAG", "Support", "Target", "TransformUtils"], add_to_library_groups = ["Lanai"], name = "LanaiCodeGen")
    ctx.target_group(ctx, name = "Lanai", parent = "Target")
    ctx.library(ctx, add_to_library_groups = ["Lanai"], name = "LanaiAsmParser", parent = "Lanai", required_libraries = ["MC", "MCParser", "Support", "LanaiDesc", "LanaiInfo"])
    ctx.library(ctx, add_to_library_groups = ["Lanai"], name = "LanaiDisassembler", parent = "Lanai", required_libraries = ["LanaiDesc", "LanaiInfo", "MC", "MCDisassembler", "Support"])
    ctx.library(ctx, required_libraries = ["LanaiInfo", "MC", "MCDisassembler", "Support"], add_to_library_groups = ["Lanai"], name = "LanaiDesc", parent = "Lanai")
    ctx.library(ctx, required_libraries = ["Support"], add_to_library_groups = ["Lanai"], name = "LanaiInfo", parent = "Lanai")
    ctx.target_group(ctx, name = "Hexagon", parent = "Target")
    ctx.library(ctx, required_libraries = ["Analysis", "AsmPrinter", "CodeGen", "Core", "HexagonAsmParser", "HexagonDesc", "HexagonInfo", "IPO", "MC", "Scalar", "SelectionDAG", "Support", "Target", "TransformUtils"], add_to_library_groups = ["Hexagon"], name = "HexagonCodeGen", parent = "Hexagon")
    ctx.library(ctx, name = "HexagonAsmParser", parent = "Hexagon", required_libraries = ["MC", "MCParser", "Support", "HexagonDesc", "HexagonInfo"], add_to_library_groups = ["Hexagon"])
    ctx.library(ctx, required_libraries = ["HexagonDesc", "HexagonInfo", "MC", "MCDisassembler", "Support"], add_to_library_groups = ["Hexagon"], name = "HexagonDisassembler", parent = "Hexagon")
    ctx.library(ctx, name = "HexagonDesc", parent = "Hexagon", required_libraries = ["HexagonInfo", "MC", "Support"], add_to_library_groups = ["Hexagon"])
    ctx.library(ctx, name = "HexagonInfo", parent = "Hexagon", required_libraries = ["Support"], add_to_library_groups = ["Hexagon"])
    ctx.target_group(ctx, name = "MSP430", parent = "Target")
    ctx.library(ctx, required_libraries = ["AsmPrinter", "CodeGen", "Core", "MC", "MSP430Desc", "MSP430Info", "SelectionDAG", "Support", "Target"], add_to_library_groups = ["MSP430"], name = "MSP430CodeGen", parent = "MSP430")
    ctx.library(ctx, name = "MSP430AsmParser", parent = "MSP430", required_libraries = ["MC", "MCParser", "MSP430Desc", "MSP430Info", "Support"], add_to_library_groups = ["MSP430"])
    ctx.library(ctx, required_libraries = ["MCDisassembler", "MSP430Info", "Support"], add_to_library_groups = ["MSP430"], name = "MSP430Disassembler", parent = "MSP430")
    ctx.library(ctx, name = "MSP430Desc", parent = "MSP430", required_libraries = ["MC", "MSP430Info", "Support"], add_to_library_groups = ["MSP430"])
    ctx.library(ctx, parent = "MSP430", required_libraries = ["Support"], add_to_library_groups = ["MSP430"], name = "MSP430Info")
    ctx.target_group(ctx, name = "NVPTX", parent = "Target")
    ctx.library(ctx, required_libraries = ["Analysis", "AsmPrinter", "CodeGen", "Core", "IPO", "MC", "NVPTXDesc", "NVPTXInfo", "Scalar", "SelectionDAG", "Support", "Target", "TransformUtils", "Vectorize"], add_to_library_groups = ["NVPTX"], name = "NVPTXCodeGen", parent = "NVPTX")
    ctx.library(ctx, required_libraries = ["MC", "NVPTXInfo", "Support"], add_to_library_groups = ["NVPTX"], name = "NVPTXDesc", parent = "NVPTX")
    ctx.library(ctx, name = "NVPTXInfo", parent = "NVPTX", required_libraries = ["Support"], add_to_library_groups = ["NVPTX"])
    ctx.target_group(ctx, name = "Mips", parent = "Target")
    ctx.library(ctx, parent = "Mips", required_libraries = ["Analysis", "AsmPrinter", "CodeGen", "Core", "MC", "MipsDesc", "MipsInfo", "SelectionDAG", "Support", "Target", "GlobalISel"], add_to_library_groups = ["Mips"], name = "MipsCodeGen")
    ctx.library(ctx, name = "MipsAsmParser", parent = "Mips", required_libraries = ["MC", "MCParser", "MipsDesc", "MipsInfo", "Support"], add_to_library_groups = ["Mips"])
    ctx.library(ctx, parent = "Mips", required_libraries = ["MCDisassembler", "MipsInfo", "Support"], add_to_library_groups = ["Mips"], name = "MipsDisassembler")
    ctx.library(ctx, name = "MipsDesc", parent = "Mips", required_libraries = ["MC", "MipsInfo", "Support"], add_to_library_groups = ["Mips"])
    ctx.library(ctx, add_to_library_groups = ["Mips"], name = "MipsInfo", parent = "Mips", required_libraries = ["Support"])
    ctx.target_group(ctx, name = "PowerPC", parent = "Target")
    ctx.library(ctx, parent = "PowerPC", required_libraries = ["Analysis", "AsmPrinter", "CodeGen", "Core", "MC", "PowerPCDesc", "PowerPCInfo", "Scalar", "SelectionDAG", "Support", "Target", "TransformUtils"], add_to_library_groups = ["PowerPC"], name = "PowerPCCodeGen")
    ctx.library(ctx, add_to_library_groups = ["PowerPC"], name = "PowerPCAsmParser", parent = "PowerPC", required_libraries = ["MC", "MCParser", "PowerPCDesc", "PowerPCInfo", "Support"])
    ctx.library(ctx, name = "PowerPCDisassembler", parent = "PowerPC", required_libraries = ["MCDisassembler", "PowerPCInfo", "Support"], add_to_library_groups = ["PowerPC"])
    ctx.library(ctx, required_libraries = ["MC", "PowerPCInfo", "Support"], add_to_library_groups = ["PowerPC"], name = "PowerPCDesc", parent = "PowerPC")
    ctx.library(ctx, required_libraries = ["Support"], add_to_library_groups = ["PowerPC"], name = "PowerPCInfo", parent = "PowerPC")
    ctx.target_group(ctx, name = "RISCV", parent = "Target")
    ctx.library(ctx, name = "RISCVCodeGen", parent = "RISCV", required_libraries = ["Analysis", "AsmPrinter", "Core", "CodeGen", "MC", "RISCVDesc", "RISCVInfo", "RISCVUtils", "SelectionDAG", "Support", "Target", "GlobalISel"], add_to_library_groups = ["RISCV"])
    ctx.library(ctx, add_to_library_groups = ["RISCV"], name = "RISCVAsmParser", parent = "RISCV", required_libraries = ["MC", "MCParser", "RISCVDesc", "RISCVInfo", "RISCVUtils", "Support"])
    ctx.library(ctx, required_libraries = ["MCDisassembler", "RISCVInfo", "Support"], add_to_library_groups = ["RISCV"], name = "RISCVDisassembler", parent = "RISCV")
    ctx.library(ctx, add_to_library_groups = ["RISCV"], name = "RISCVInfo", parent = "RISCV", required_libraries = ["Support"])
    ctx.library(ctx, required_libraries = ["MC", "RISCVInfo", "RISCVUtils", "Support"], add_to_library_groups = ["RISCV"], name = "RISCVDesc", parent = "RISCV")
    ctx.library(ctx, add_to_library_groups = ["RISCV"], name = "RISCVUtils", parent = "RISCV", required_libraries = ["Support"])
    ctx.library(ctx, parent = "Sparc", required_libraries = ["AsmPrinter", "CodeGen", "Core", "MC", "SelectionDAG", "SparcDesc", "SparcInfo", "Support", "Target"], add_to_library_groups = ["Sparc"], name = "SparcCodeGen")
    ctx.target_group(ctx, name = "Sparc", parent = "Target")
    ctx.library(ctx, name = "SparcAsmParser", parent = "Sparc", required_libraries = ["MC", "MCParser", "SparcDesc", "SparcInfo", "Support"], add_to_library_groups = ["Sparc"])
    ctx.library(ctx, required_libraries = ["MCDisassembler", "SparcInfo", "Support"], add_to_library_groups = ["Sparc"], name = "SparcDisassembler", parent = "Sparc")
    ctx.library(ctx, add_to_library_groups = ["Sparc"], name = "SparcDesc", parent = "Sparc", required_libraries = ["MC", "SparcInfo", "Support"])
    ctx.library(ctx, required_libraries = ["Support"], add_to_library_groups = ["Sparc"], name = "SparcInfo", parent = "Sparc")
    ctx.target_group(ctx, name = "SystemZ", parent = "Target")
    ctx.library(ctx, required_libraries = ["Analysis", "AsmPrinter", "CodeGen", "Core", "MC", "Scalar", "SelectionDAG", "Support", "SystemZDesc", "SystemZInfo", "Target"], add_to_library_groups = ["SystemZ"], name = "SystemZCodeGen", parent = "SystemZ")
    ctx.library(ctx, name = "SystemZAsmParser", parent = "SystemZ", required_libraries = ["MC", "MCParser", "Support", "SystemZDesc", "SystemZInfo"], add_to_library_groups = ["SystemZ"])
    ctx.library(ctx, name = "SystemZDisassembler", parent = "SystemZ", required_libraries = ["MC", "MCDisassembler", "Support", "SystemZDesc", "SystemZInfo"], add_to_library_groups = ["SystemZ"])
    ctx.library(ctx, name = "SystemZDesc", parent = "SystemZ", required_libraries = ["MC", "Support", "SystemZInfo"], add_to_library_groups = ["SystemZ"])
    ctx.library(ctx, add_to_library_groups = ["SystemZ"], name = "SystemZInfo", parent = "SystemZ", required_libraries = ["Support"])
    ctx.target_group(ctx, name = "WebAssembly", parent = "Target")
    ctx.library(ctx, required_libraries = ["Analysis", "AsmPrinter", "BinaryFormat", "CodeGen", "Core", "MC", "Scalar", "SelectionDAG", "Support", "Target", "TransformUtils", "WebAssemblyDesc", "WebAssemblyInfo"], add_to_library_groups = ["WebAssembly"], name = "WebAssemblyCodeGen", parent = "WebAssembly")
    ctx.library(ctx, name = "WebAssemblyAsmParser", parent = "WebAssembly", required_libraries = ["MC", "MCParser", "WebAssemblyInfo", "Support"], add_to_library_groups = ["WebAssembly"])
    ctx.library(ctx, required_libraries = ["WebAssemblyDesc", "MCDisassembler", "WebAssemblyInfo", "Support", "MC"], add_to_library_groups = ["WebAssembly"], name = "WebAssemblyDisassembler", parent = "WebAssembly")
    ctx.library(ctx, name = "WebAssemblyDesc", parent = "WebAssembly", required_libraries = ["MC", "Support", "WebAssemblyInfo"], add_to_library_groups = ["WebAssembly"])
    ctx.library(ctx, name = "WebAssemblyInfo", parent = "WebAssembly", required_libraries = ["Support"], add_to_library_groups = ["WebAssembly"])
    ctx.target_group(ctx, name = "X86", parent = "Target")
    ctx.library(ctx, name = "X86CodeGen", parent = "X86", required_libraries = ["Analysis", "AsmPrinter", "CodeGen", "Core", "MC", "SelectionDAG", "Support", "Target", "X86Desc", "X86Info", "X86Utils", "GlobalISel", "ProfileData", "CFGuard"], add_to_library_groups = ["X86"])
    ctx.library(ctx, required_libraries = ["MC", "MCParser", "Support", "X86Desc", "X86Info"], add_to_library_groups = ["X86"], name = "X86AsmParser", parent = "X86")
    ctx.library(ctx, name = "X86Disassembler", parent = "X86", required_libraries = ["MCDisassembler", "Support", "X86Info"], add_to_library_groups = ["X86"])
    ctx.library(ctx, name = "X86Desc", parent = "X86", required_libraries = ["MC", "MCDisassembler", "Object", "Support", "X86Info", "X86Utils"], add_to_library_groups = ["X86"])
    ctx.library(ctx, parent = "X86", required_libraries = ["Support"], add_to_library_groups = ["X86"], name = "X86Info")
    ctx.library(ctx, add_to_library_groups = ["X86"], name = "X86Utils", parent = "X86", required_libraries = ["Support"])
    ctx.target_group(ctx, name = "XCore", parent = "Target")
    ctx.library(ctx, add_to_library_groups = ["XCore"], name = "XCoreCodeGen", parent = "XCore", required_libraries = ["Analysis", "AsmPrinter", "CodeGen", "Core", "MC", "SelectionDAG", "Support", "Target", "TransformUtils", "XCoreDesc", "XCoreInfo"])
    ctx.library(ctx, name = "XCoreDisassembler", parent = "XCore", required_libraries = ["MCDisassembler", "Support", "XCoreInfo"], add_to_library_groups = ["XCore"])
    ctx.library(ctx, name = "XCoreDesc", parent = "XCore", required_libraries = ["MC", "Support", "XCoreInfo"], add_to_library_groups = ["XCore"])
    ctx.library(ctx, name = "XCoreInfo", parent = "XCore", required_libraries = ["Support"], add_to_library_groups = ["XCore"])
    ctx.library(ctx, name = "TestingSupport", parent = "Libraries", required_libraries = ["Support"])
    ctx.group(ctx, name = "ToolDrivers", parent = "Libraries")
    ctx.library(ctx, name = "DlltoolDriver", parent = "Libraries", required_libraries = ["Object", "Option", "Support"])
    ctx.library(ctx, required_libraries = ["BinaryFormat", "BitReader", "Object", "Option", "Support"], name = "LibDriver", parent = "Libraries")
    ctx.group(ctx, name = "Transforms", parent = "Libraries")
    ctx.library(ctx, name = "AggressiveInstCombine", parent = "Transforms", required_libraries = ["Analysis", "Core", "Support", "TransformUtils"])
    ctx.library(ctx, required_libraries = ["Analysis", "Core", "IPO", "Scalar", "Support", "TransformUtils"], name = "Coroutines", parent = "Transforms")
    ctx.library(ctx, name = "IPO", parent = "Transforms", library_name = "ipo", required_libraries = ["AggressiveInstCombine", "Analysis", "BitReader", "BitWriter", "Core", "InstCombine", "IRReader", "Linker", "Object", "ProfileData", "Scalar", "Support", "TransformUtils", "Vectorize", "Instrumentation"])
    ctx.library(ctx, parent = "Transforms", required_libraries = ["Analysis", "Core", "Support", "TransformUtils"], name = "InstCombine")
    ctx.library(ctx, parent = "Transforms", required_libraries = ["Analysis", "Core", "MC", "Support", "TransformUtils", "ProfileData"], name = "Instrumentation")
    ctx.library(ctx, library_name = "ScalarOpts", required_libraries = ["AggressiveInstCombine", "Analysis", "Core", "InstCombine", "Support", "TransformUtils"], name = "Scalar", parent = "Transforms")
    ctx.library(ctx, name = "TransformUtils", parent = "Transforms", required_libraries = ["Analysis", "Core", "Support"])
    ctx.library(ctx, library_name = "Vectorize", required_libraries = ["Analysis", "Core", "Support", "TransformUtils"], name = "Vectorize", parent = "Transforms")
    ctx.library(ctx, required_libraries = ["Analysis", "Core", "Support", "TransformUtils"], name = "ObjCARC", parent = "Transforms", library_name = "ObjCARCOpts")
    ctx.library(ctx, name = "CFGuard", parent = "Transforms", required_libraries = ["Core", "Support"])
    ctx.library(ctx, name = "WindowsManifest", parent = "Libraries", required_libraries = ["Support"])
    ctx.library(ctx, required_libraries = ["Support", "Object"], name = "XRay", parent = "Libraries")
    ctx.group(ctx, name = "Projects", parent = "$ROOT")
    ctx.group(ctx, name = "Tools", parent = "$ROOT")
    ctx.tool(ctx, parent = "Tools", required_libraries = ["AsmParser", "BitReader", "BitWriter", "CodeGen", "IRReader", "IPO", "Instrumentation", "Linker", "ObjCARC", "Scalar", "all-targets"], name = "bugpoint")
    ctx.tool(ctx, name = "dsymutil", parent = "Tools", required_libraries = ["AsmPrinter", "DebugInfoDWARF", "MC", "Object", "CodeGen", "Support", "all-targets"])
    ctx.tool(ctx, name = "llc", parent = "Tools", required_libraries = ["AsmParser", "BitReader", "IRReader", "MIRParser", "TransformUtils", "Scalar", "Vectorize", "all-targets"])
    ctx.tool(ctx, name = "lli", parent = "Tools", required_libraries = ["AsmParser", "BitReader", "IRReader", "Instrumentation", "Interpreter", "MCJIT", "Native", "NativeCodeGen", "SelectionDAG", "TransformUtils"])
    ctx.tool(ctx, parent = "lli", name = "lli-child-target")
    ctx.tool(ctx, name = "llvm-ar", parent = "Tools")
    ctx.tool(ctx, required_libraries = ["AsmParser", "BitWriter"], name = "llvm-as", parent = "Tools")
    ctx.tool(ctx, name = "llvm-bcanalyzer", parent = "Tools", required_libraries = ["BitReader", "BitstreamReader", "Support"])
    ctx.tool(ctx, parent = "Tools", required_libraries = ["AsmParser", "BitReader", "BitWriter"], name = "llvm-cat")
    ctx.tool(ctx, parent = "Tools", required_libraries = ["all-targets", "MC", "MCDisassembler", "MCParser", "Support", "Symbolize"], name = "llvm-cfi-verify")
    ctx.tool(ctx, parent = "Tools", required_libraries = ["Coverage", "Support", "Instrumentation"], name = "llvm-cov")
    ctx.tool(ctx, required_libraries = ["Object", "Option", "Support"], name = "llvm-cvtres", parent = "Tools")
    ctx.tool(ctx, name = "llvm-diff", parent = "Tools", required_libraries = ["AsmParser", "BitReader", "IRReader"])
    ctx.tool(ctx, name = "llvm-dis", parent = "Tools", required_libraries = ["Analysis", "BitReader"])
    ctx.tool(ctx, name = "llvm-dwarfdump", parent = "Tools", required_libraries = ["DebugInfoDWARF", "Object"])
    ctx.tool(ctx, required_libraries = ["AsmPrinter", "DebugInfoDWARF", "MC", "Object", "Support", "all-targets"], name = "llvm-dwp", parent = "Tools")
    ctx.tool(ctx, name = "llvm-elfabi", parent = "Tools", required_libraries = ["Object", "Support", "TextAPI"])
    ctx.tool(ctx, name = "llvm-ifs", parent = "Tools", required_libraries = ["Object", "Support", "TextAPI"])
    ctx.tool(ctx, name = "llvm-exegesis", parent = "Tools", required_libraries = ["CodeGen", "ExecutionEngine", "MC", "MCJIT", "Native", "NativeCodeGen", "Object", "Support"])
    ctx.tool(ctx, parent = "Tools", required_libraries = ["AsmParser", "BitReader", "BitWriter", "IRReader", "IPO"], name = "llvm-extract")
    ctx.tool(ctx, name = "llvm-jitlistener", parent = "Tools", required_libraries = ["AsmParser", "BitReader", "IRReader", "Interpreter", "MCJIT", "NativeCodeGen", "Object", "SelectionDAG", "Native"])
    ctx.tool(ctx, name = "llvm-jitlink", parent = "Tools", required_libraries = ["JITLink", "BinaryFormat", "MC", "Object", "RuntimeDyld", "Support", "all-targets"])
    ctx.tool(ctx, name = "llvm-link", parent = "Tools", required_libraries = ["AsmParser", "BitReader", "BitWriter", "IRReader", "Linker", "Object", "TransformUtils", "IPO"])
    ctx.tool(ctx, name = "llvm-lto", parent = "Tools", required_libraries = ["BitWriter", "Core", "IRReader", "LTO", "Object", "Support", "all-targets"])
    ctx.tool(ctx, name = "llvm-mc", parent = "Tools", required_libraries = ["MC", "MCDisassembler", "MCParser", "Support", "all-targets"])
    ctx.tool(ctx, required_libraries = ["MC", "MCA", "MCParser", "Support", "all-targets"], name = "llvm-mca", parent = "Tools")
    ctx.tool(ctx, required_libraries = ["BitReader", "BitWriter"], name = "llvm-modextract", parent = "Tools")
    ctx.tool(ctx, parent = "Tools", required_libraries = ["Option", "Support", "WindowsManifest"], name = "llvm-mt")
    ctx.tool(ctx, name = "llvm-nm", parent = "Tools", required_libraries = ["BitReader", "Object"])
    ctx.tool(ctx, name = "llvm-objcopy", parent = "Tools", required_libraries = ["Object", "Option", "Support", "MC"])
    ctx.tool(ctx, parent = "Tools", required_libraries = ["DebugInfoDWARF", "MC", "MCDisassembler", "MCParser", "Object", "all-targets", "Demangle"], name = "llvm-objdump")
    ctx.tool(ctx, name = "llvm-pdbutil", parent = "Tools", required_libraries = ["DebugInfoMSF", "DebugInfoPDB"])
    ctx.tool(ctx, name = "llvm-profdata", parent = "Tools", required_libraries = ["ProfileData", "Support"])
    ctx.tool(ctx, name = "llvm-rc", parent = "Tools", required_libraries = ["Option"])
    ctx.tool(ctx, name = "llvm-reduce", parent = "Tools", required_libraries = ["BitReader", "IRReader", "all-targets"])
    ctx.tool(ctx, parent = "Tools", required_libraries = ["MC", "Object", "RuntimeDyld", "Support", "all-targets"], name = "llvm-rtdyld")
    ctx.tool(ctx, name = "llvm-size", parent = "Tools", required_libraries = ["Object"])
    ctx.tool(ctx, required_libraries = ["TransformUtils", "BitWriter", "Core", "IRReader", "Support"], name = "llvm-split", parent = "Tools")
    ctx.tool(ctx, name = "llvm-undname", parent = "Tools", required_libraries = ["Demangle", "Support"])
    ctx.tool(ctx, parent = "Tools", required_libraries = ["AsmParser", "BitReader", "BitWriter", "CodeGen", "IRReader", "IPO", "Instrumentation", "Scalar", "ObjCARC", "Passes", "all-targets"], name = "opt")
    ctx.tool(ctx, name = "verify-uselistorder", parent = "Tools", required_libraries = ["IRReader", "BitWriter", "Support"])
    ctx.group(ctx, parent = "$ROOT", name = "BuildTools")
    ctx.group(ctx, name = "UtilityTools", parent = "$ROOT")
    ctx.build_tool(ctx, name = "tblgen", parent = "BuildTools", required_libraries = ["Support", "TableGen", "MC"])
    ctx.library(ctx, name = "gtest", parent = "Libraries", required_libraries = ["Support"])
    ctx.library(ctx, parent = "Libraries", required_libraries = ["gtest"], name = "gtest_main")
    return ctx
