load("//tools:build_rules/go.bzl", "go_package")

package(default_visibility = ["//kythe:default_visibility"])

go_package(
    deps = [
        "@go_protobuf//:jsonpb",
        "@go_protobuf//:proto",
        "//kythe/go/util/httpencoding",
    ],
)
