load("//tools:build_rules/shims.bzl", "go_library", "go_test")
load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load("//tools:build_rules/shims.bzl", "go_library")

package(default_visibility = ["//kythe:default_visibility"])

go_library(
    name = "log",
    srcs = ["log.go"],
)
