load("//tools:build_rules/shims.bzl", "go_library")

package(default_visibility = ["//kythe:default_visibility"])

go_library(
    name = "log",
    srcs = ["log.go"],
    importpath = "kythe.io/kythe/go/util/log",
)
