load("//tools:build_rules/shims.bzl", "go_library")

package(default_visibility = ["//kythe:default_visibility"])

go_library(
    name = "flags",
    srcs = ["encoding.go"],
    deps = [
        "//kythe/go/platform/kzip",
    ],
)
