load("//tools:build_rules/go.bzl", "go_package_library")

package(default_visibility = ["//kythe:default_visibility"])

go_package_library(
    name = "flagutil",
    srcs = ["flagutil.go"],
    deps = ["//kythe/go/util/build"],
)
