load("//tools:build_rules/doc.bzl", "asciidoc")

package(default_visibility = ["//kythe:default_visibility"])

asciidoc(
    name = "kythe-compatible-compilers",
    src = "kythe-compatible-compilers.txt",
)

asciidoc(
    name = "kythe-index-pack",
    src = "kythe-index-pack.txt",
)

asciidoc(
    name = "kythe-overview",
    src = "kythe-overview.txt",
)

asciidoc(
    name = "kythe-storage",
    src = "kythe-storage.txt",
)

asciidoc(
    name = "kythe-uri-spec",
    src = "kythe-uri-spec.txt",
)

asciidoc(
    name = "kythe-verifier",
    src = "kythe-verifier.txt",
)
