// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kythe/proto/driver.proto

package driver_go_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import analysis_go_proto "kythe.io/kythe/proto/analysis_go_proto"
import common_go_proto "kythe.io/kythe/proto/common_go_proto"
import storage_go_proto "kythe.io/kythe/proto/storage_go_proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InitRequest struct {
	Protocol             string   `protobuf:"bytes,1,opt,name=protocol" json:"protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitRequest) Reset()         { *m = InitRequest{} }
func (m *InitRequest) String() string { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()    {}
func (*InitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_84f1ea3c817fd371, []int{0}
}
func (m *InitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRequest.Unmarshal(m, b)
}
func (m *InitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRequest.Marshal(b, m, deterministic)
}
func (dst *InitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRequest.Merge(dst, src)
}
func (m *InitRequest) XXX_Size() int {
	return xxx_messageInfo_InitRequest.Size(m)
}
func (m *InitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitRequest proto.InternalMessageInfo

func (m *InitRequest) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

type InitReply struct {
	Protocol             string   `protobuf:"bytes,1,opt,name=protocol" json:"protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitReply) Reset()         { *m = InitReply{} }
func (m *InitReply) String() string { return proto.CompactTextString(m) }
func (*InitReply) ProtoMessage()    {}
func (*InitReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_84f1ea3c817fd371, []int{1}
}
func (m *InitReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitReply.Unmarshal(m, b)
}
func (m *InitReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitReply.Marshal(b, m, deterministic)
}
func (dst *InitReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitReply.Merge(dst, src)
}
func (m *InitReply) XXX_Size() int {
	return xxx_messageInfo_InitReply.Size(m)
}
func (m *InitReply) XXX_DiscardUnknown() {
	xxx_messageInfo_InitReply.DiscardUnknown(m)
}

var xxx_messageInfo_InitReply proto.InternalMessageInfo

func (m *InitReply) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

type AnalyzeRequest struct {
	Language             string   `protobuf:"bytes,1,opt,name=language" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnalyzeRequest) Reset()         { *m = AnalyzeRequest{} }
func (m *AnalyzeRequest) String() string { return proto.CompactTextString(m) }
func (*AnalyzeRequest) ProtoMessage()    {}
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_84f1ea3c817fd371, []int{2}
}
func (m *AnalyzeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzeRequest.Unmarshal(m, b)
}
func (m *AnalyzeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzeRequest.Marshal(b, m, deterministic)
}
func (dst *AnalyzeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzeRequest.Merge(dst, src)
}
func (m *AnalyzeRequest) XXX_Size() int {
	return xxx_messageInfo_AnalyzeRequest.Size(m)
}
func (m *AnalyzeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzeRequest proto.InternalMessageInfo

func (m *AnalyzeRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type AnalyzeReply struct {
	Id                   int64                              `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Unit                 *analysis_go_proto.CompilationUnit `protobuf:"bytes,2,opt,name=unit" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *AnalyzeReply) Reset()         { *m = AnalyzeReply{} }
func (m *AnalyzeReply) String() string { return proto.CompactTextString(m) }
func (*AnalyzeReply) ProtoMessage()    {}
func (*AnalyzeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_84f1ea3c817fd371, []int{3}
}
func (m *AnalyzeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzeReply.Unmarshal(m, b)
}
func (m *AnalyzeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzeReply.Marshal(b, m, deterministic)
}
func (dst *AnalyzeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzeReply.Merge(dst, src)
}
func (m *AnalyzeReply) XXX_Size() int {
	return xxx_messageInfo_AnalyzeReply.Size(m)
}
func (m *AnalyzeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzeReply.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzeReply proto.InternalMessageInfo

func (m *AnalyzeReply) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AnalyzeReply) GetUnit() *analysis_go_proto.CompilationUnit {
	if m != nil {
		return m.Unit
	}
	return nil
}

type FileRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Digest               string   `protobuf:"bytes,3,opt,name=digest" json:"digest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileRequest) Reset()         { *m = FileRequest{} }
func (m *FileRequest) String() string { return proto.CompactTextString(m) }
func (*FileRequest) ProtoMessage()    {}
func (*FileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_84f1ea3c817fd371, []int{4}
}
func (m *FileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileRequest.Unmarshal(m, b)
}
func (m *FileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileRequest.Marshal(b, m, deterministic)
}
func (dst *FileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileRequest.Merge(dst, src)
}
func (m *FileRequest) XXX_Size() int {
	return xxx_messageInfo_FileRequest.Size(m)
}
func (m *FileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileRequest proto.InternalMessageInfo

func (m *FileRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FileRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *FileRequest) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

type FileReply struct {
	Path                 string   `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Digest               string   `protobuf:"bytes,3,opt,name=digest" json:"digest,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileReply) Reset()         { *m = FileReply{} }
func (m *FileReply) String() string { return proto.CompactTextString(m) }
func (*FileReply) ProtoMessage()    {}
func (*FileReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_84f1ea3c817fd371, []int{5}
}
func (m *FileReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileReply.Unmarshal(m, b)
}
func (m *FileReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileReply.Marshal(b, m, deterministic)
}
func (dst *FileReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileReply.Merge(dst, src)
}
func (m *FileReply) XXX_Size() int {
	return xxx_messageInfo_FileReply.Size(m)
}
func (m *FileReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FileReply.DiscardUnknown(m)
}

var xxx_messageInfo_FileReply proto.InternalMessageInfo

func (m *FileReply) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *FileReply) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *FileReply) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type OutRequest struct {
	Id                   int64                     `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Output               [][]byte                  `protobuf:"bytes,2,rep,name=output,proto3" json:"output,omitempty"`
	Entries              []*storage_go_proto.Entry `protobuf:"bytes,3,rep,name=entries" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *OutRequest) Reset()         { *m = OutRequest{} }
func (m *OutRequest) String() string { return proto.CompactTextString(m) }
func (*OutRequest) ProtoMessage()    {}
func (*OutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_84f1ea3c817fd371, []int{6}
}
func (m *OutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutRequest.Unmarshal(m, b)
}
func (m *OutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutRequest.Marshal(b, m, deterministic)
}
func (dst *OutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutRequest.Merge(dst, src)
}
func (m *OutRequest) XXX_Size() int {
	return xxx_messageInfo_OutRequest.Size(m)
}
func (m *OutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OutRequest proto.InternalMessageInfo

func (m *OutRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OutRequest) GetOutput() [][]byte {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *OutRequest) GetEntries() []*storage_go_proto.Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type LogRequest struct {
	Id                   int64                       `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Message              *common_go_proto.Diagnostic `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *LogRequest) Reset()         { *m = LogRequest{} }
func (m *LogRequest) String() string { return proto.CompactTextString(m) }
func (*LogRequest) ProtoMessage()    {}
func (*LogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_84f1ea3c817fd371, []int{7}
}
func (m *LogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogRequest.Unmarshal(m, b)
}
func (m *LogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogRequest.Marshal(b, m, deterministic)
}
func (dst *LogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogRequest.Merge(dst, src)
}
func (m *LogRequest) XXX_Size() int {
	return xxx_messageInfo_LogRequest.Size(m)
}
func (m *LogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogRequest proto.InternalMessageInfo

func (m *LogRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LogRequest) GetMessage() *common_go_proto.Diagnostic {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*InitRequest)(nil), "kythe.driver.InitRequest")
	proto.RegisterType((*InitReply)(nil), "kythe.driver.InitReply")
	proto.RegisterType((*AnalyzeRequest)(nil), "kythe.driver.AnalyzeRequest")
	proto.RegisterType((*AnalyzeReply)(nil), "kythe.driver.AnalyzeReply")
	proto.RegisterType((*FileRequest)(nil), "kythe.driver.FileRequest")
	proto.RegisterType((*FileReply)(nil), "kythe.driver.FileReply")
	proto.RegisterType((*OutRequest)(nil), "kythe.driver.OutRequest")
	proto.RegisterType((*LogRequest)(nil), "kythe.driver.LogRequest")
}

func init() { proto.RegisterFile("kythe/proto/driver.proto", fileDescriptor_driver_84f1ea3c817fd371) }

var fileDescriptor_driver_84f1ea3c817fd371 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x6b, 0xab, 0x40,
	0x10, 0xc7, 0x31, 0x86, 0xe4, 0x39, 0x4a, 0x0e, 0x1e, 0x82, 0x4f, 0x1e, 0x0f, 0xf1, 0x52, 0x0b,
	0xc1, 0x94, 0xf4, 0xd2, 0x6b, 0xe9, 0x0f, 0x08, 0x2d, 0xb4, 0x2c, 0xb4, 0xf7, 0x4d, 0x5c, 0xcc,
	0x52, 0xdd, 0xb5, 0xee, 0x58, 0xb0, 0x7f, 0x7d, 0x71, 0x57, 0x43, 0x52, 0x48, 0xa1, 0xb7, 0xf9,
	0xce, 0x7c, 0xfc, 0xce, 0xd7, 0x51, 0x08, 0xde, 0x5a, 0xdc, 0xb1, 0x65, 0x55, 0x4b, 0x94, 0xcb,
	0xac, 0xe6, 0x1f, 0xac, 0x4e, 0xb5, 0xf0, 0x3d, 0x3d, 0x49, 0x4d, 0x2f, 0x0c, 0x0f, 0x39, 0x2a,
	0x68, 0xd1, 0x2a, 0xae, 0x0c, 0x19, 0x1e, 0x79, 0x6c, 0x65, 0x59, 0x4a, 0xd1, 0x4f, 0xfe, 0x1e,
	0x4e, 0x14, 0xca, 0x9a, 0xe6, 0xcc, 0x8c, 0xe2, 0x73, 0x70, 0xd7, 0x82, 0x23, 0x61, 0xef, 0x0d,
	0x53, 0xe8, 0x87, 0xf0, 0x47, 0xf7, 0xb7, 0xb2, 0x08, 0xac, 0xc8, 0x4a, 0x1c, 0xb2, 0xd7, 0xf1,
	0x19, 0x38, 0x06, 0xad, 0x8a, 0xf6, 0x47, 0x70, 0x01, 0xb3, 0xeb, 0x2e, 0xda, 0x27, 0x3b, 0xb0,
	0x2d, 0xa8, 0xc8, 0x1b, 0x9a, 0xb3, 0x81, 0x1e, 0x74, 0xfc, 0x0c, 0xde, 0x9e, 0xee, 0x9c, 0x67,
	0x30, 0xe2, 0x99, 0xa6, 0x6c, 0x32, 0xe2, 0x99, 0x7f, 0x01, 0xe3, 0x46, 0x70, 0x0c, 0x46, 0x91,
	0x95, 0xb8, 0xab, 0x7f, 0xa9, 0xb9, 0x87, 0x5e, 0x96, 0xde, 0xc8, 0xb2, 0xe2, 0x05, 0x45, 0x2e,
	0xc5, 0x4b, 0x17, 0x4d, 0x93, 0xf1, 0x1a, 0xdc, 0x7b, 0x5e, 0xec, 0x97, 0x7f, 0x37, 0xf4, 0x61,
	0x5c, 0x51, 0xdc, 0x69, 0x43, 0x87, 0xe8, 0xda, 0x9f, 0xc3, 0x24, 0xe3, 0x39, 0x53, 0x18, 0xd8,
	0xba, 0xdb, 0xab, 0xf8, 0x01, 0x1c, 0x63, 0xd5, 0x25, 0xfb, 0xc5, 0x83, 0x1d, 0x9b, 0x51, 0xa4,
	0xc1, 0x38, 0xb2, 0x12, 0x8f, 0xe8, 0x3a, 0xde, 0x00, 0x3c, 0x35, 0x78, 0x2a, 0xd6, 0x1c, 0x26,
	0xb2, 0xc1, 0xaa, 0xe9, 0xde, 0xd4, 0x4e, 0x3c, 0xd2, 0x2b, 0x7f, 0x01, 0x53, 0x26, 0xb0, 0xe6,
	0x4c, 0x05, 0x76, 0x64, 0x27, 0xee, 0xca, 0x3f, 0x3a, 0xc1, 0x9d, 0xc0, 0xba, 0x25, 0x03, 0x12,
	0xbf, 0x02, 0x3c, 0xca, 0xfc, 0xd4, 0x8e, 0x2b, 0x98, 0x96, 0x4c, 0xa9, 0xee, 0x33, 0x98, 0x73,
	0xfe, 0x3f, 0xf2, 0xea, 0x7f, 0x9a, 0x5b, 0x4e, 0x73, 0x21, 0x15, 0xf2, 0x2d, 0x19, 0xf0, 0xcd,
	0x44, 0x13, 0x97, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x97, 0x7a, 0x80, 0xa8, 0xa9, 0x02, 0x00,
	0x00,
}
