sh_test(
    name = "kwazthis_test",
    srcs = ["kwazthis_test.sh"],
    data = [
        "//kythe/cxx/common/testdata:start_http_service",
        "//kythe/go/platform/tools:entrystream",
        "//kythe/go/serving/tools:kwazthis",
        "//kythe/go/serving/tools:write_tables",
        "//kythe/go/storage/tools:write_entries",
        "//kythe/go/test/tools:http_server",
        "//kythe/javatests/com/google/devtools/kythe/analyzers/java/testdata/pkg:generics_tests",
        "//third_party/jq",
    ],
)
