package(default_visibility = ["//kythe:default_visibility"])

# Built externally, if enabled.
filegroup(
    name = "ts_indexer",
    srcs = glob([
        "build/**/*",
        "node_modules/**/*",
        "typings/**/*",
    ]),
)
