# Stub the required Android tools until they are no longer required.
# See https://github.com/google/bazel/issues/249.

filegroup(name = "sdk")

filegroup(name = "aar_generator")

filegroup(name = "resources_processor")

filegroup(name = "incremental_stub_application")

filegroup(name = "incremental_split_stub_application")
