load("//tools:build_rules/go.bzl", "go_package")

package(default_visibility = ["//kythe:default_visibility"])

go_package(
    deps = [
        "@go_snappy//:snappy",
        "//kythe/go/platform/delimited",
        "//kythe/go/util/sortutil",
    ],
)
