// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kythe/proto/common.proto

package common_go_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Link_Kind int32

const (
	Link_DEFINITION Link_Kind = 0
	Link_LIST       Link_Kind = 1
	Link_LIST_ITEM  Link_Kind = 2
	Link_IMPORTANT  Link_Kind = 999
)

var Link_Kind_name = map[int32]string{
	0:   "DEFINITION",
	1:   "LIST",
	2:   "LIST_ITEM",
	999: "IMPORTANT",
}
var Link_Kind_value = map[string]int32{
	"DEFINITION": 0,
	"LIST":       1,
	"LIST_ITEM":  2,
	"IMPORTANT":  999,
}

func (x Link_Kind) String() string {
	return proto.EnumName(Link_Kind_name, int32(x))
}
func (Link_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_common_1d80375ed42fe73a, []int{7, 0}
}

type MarkedSource_Kind int32

const (
	MarkedSource_BOX                                     MarkedSource_Kind = 0
	MarkedSource_TYPE                                    MarkedSource_Kind = 1
	MarkedSource_PARAMETER                               MarkedSource_Kind = 2
	MarkedSource_IDENTIFIER                              MarkedSource_Kind = 3
	MarkedSource_CONTEXT                                 MarkedSource_Kind = 4
	MarkedSource_INITIALIZER                             MarkedSource_Kind = 5
	MarkedSource_PARAMETER_LOOKUP_BY_PARAM               MarkedSource_Kind = 6
	MarkedSource_LOOKUP_BY_PARAM                         MarkedSource_Kind = 7
	MarkedSource_PARAMETER_LOOKUP_BY_PARAM_WITH_DEFAULTS MarkedSource_Kind = 8
	MarkedSource_LOOKUP_BY_TYPED                         MarkedSource_Kind = 9
)

var MarkedSource_Kind_name = map[int32]string{
	0: "BOX",
	1: "TYPE",
	2: "PARAMETER",
	3: "IDENTIFIER",
	4: "CONTEXT",
	5: "INITIALIZER",
	6: "PARAMETER_LOOKUP_BY_PARAM",
	7: "LOOKUP_BY_PARAM",
	8: "PARAMETER_LOOKUP_BY_PARAM_WITH_DEFAULTS",
	9: "LOOKUP_BY_TYPED",
}
var MarkedSource_Kind_value = map[string]int32{
	"BOX":                       0,
	"TYPE":                      1,
	"PARAMETER":                 2,
	"IDENTIFIER":                3,
	"CONTEXT":                   4,
	"INITIALIZER":               5,
	"PARAMETER_LOOKUP_BY_PARAM": 6,
	"LOOKUP_BY_PARAM":           7,
	"PARAMETER_LOOKUP_BY_PARAM_WITH_DEFAULTS": 8,
	"LOOKUP_BY_TYPED":                         9,
}

func (x MarkedSource_Kind) String() string {
	return proto.EnumName(MarkedSource_Kind_name, int32(x))
}
func (MarkedSource_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_common_1d80375ed42fe73a, []int{8, 0}
}

type Fact struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fact) Reset()         { *m = Fact{} }
func (m *Fact) String() string { return proto.CompactTextString(m) }
func (*Fact) ProtoMessage()    {}
func (*Fact) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_1d80375ed42fe73a, []int{0}
}
func (m *Fact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fact.Unmarshal(m, b)
}
func (m *Fact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fact.Marshal(b, m, deterministic)
}
func (dst *Fact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fact.Merge(dst, src)
}
func (m *Fact) XXX_Size() int {
	return xxx_messageInfo_Fact.Size(m)
}
func (m *Fact) XXX_DiscardUnknown() {
	xxx_messageInfo_Fact.DiscardUnknown(m)
}

var xxx_messageInfo_Fact proto.InternalMessageInfo

func (m *Fact) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Fact) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Point struct {
	ByteOffset           int32    `protobuf:"varint,1,opt,name=byte_offset,json=byteOffset,proto3" json:"byte_offset,omitempty"`
	LineNumber           int32    `protobuf:"varint,2,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`
	ColumnOffset         int32    `protobuf:"varint,3,opt,name=column_offset,json=columnOffset,proto3" json:"column_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_1d80375ed42fe73a, []int{1}
}
func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (dst *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(dst, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetByteOffset() int32 {
	if m != nil {
		return m.ByteOffset
	}
	return 0
}

func (m *Point) GetLineNumber() int32 {
	if m != nil {
		return m.LineNumber
	}
	return 0
}

func (m *Point) GetColumnOffset() int32 {
	if m != nil {
		return m.ColumnOffset
	}
	return 0
}

type Span struct {
	Start                *Point   `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  *Point   `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Span) Reset()         { *m = Span{} }
func (m *Span) String() string { return proto.CompactTextString(m) }
func (*Span) ProtoMessage()    {}
func (*Span) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_1d80375ed42fe73a, []int{2}
}
func (m *Span) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Span.Unmarshal(m, b)
}
func (m *Span) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Span.Marshal(b, m, deterministic)
}
func (dst *Span) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Span.Merge(dst, src)
}
func (m *Span) XXX_Size() int {
	return xxx_messageInfo_Span.Size(m)
}
func (m *Span) XXX_DiscardUnknown() {
	xxx_messageInfo_Span.DiscardUnknown(m)
}

var xxx_messageInfo_Span proto.InternalMessageInfo

func (m *Span) GetStart() *Point {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Span) GetEnd() *Point {
	if m != nil {
		return m.End
	}
	return nil
}

type NodeInfo struct {
	Facts                map[string][]byte `protobuf:"bytes,2,rep,name=facts,proto3" json:"facts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Definition           string            `protobuf:"bytes,5,opt,name=definition,proto3" json:"definition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_1d80375ed42fe73a, []int{3}
}
func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (dst *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(dst, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetFacts() map[string][]byte {
	if m != nil {
		return m.Facts
	}
	return nil
}

func (m *NodeInfo) GetDefinition() string {
	if m != nil {
		return m.Definition
	}
	return ""
}

type Diagnostic struct {
	Span                 *Span    `protobuf:"bytes,1,opt,name=span,proto3" json:"span,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details              string   `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	ContextUrl           string   `protobuf:"bytes,4,opt,name=context_url,json=contextUrl,proto3" json:"context_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Diagnostic) Reset()         { *m = Diagnostic{} }
func (m *Diagnostic) String() string { return proto.CompactTextString(m) }
func (*Diagnostic) ProtoMessage()    {}
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_1d80375ed42fe73a, []int{4}
}
func (m *Diagnostic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Diagnostic.Unmarshal(m, b)
}
func (m *Diagnostic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Diagnostic.Marshal(b, m, deterministic)
}
func (dst *Diagnostic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Diagnostic.Merge(dst, src)
}
func (m *Diagnostic) XXX_Size() int {
	return xxx_messageInfo_Diagnostic.Size(m)
}
func (m *Diagnostic) XXX_DiscardUnknown() {
	xxx_messageInfo_Diagnostic.DiscardUnknown(m)
}

var xxx_messageInfo_Diagnostic proto.InternalMessageInfo

func (m *Diagnostic) GetSpan() *Span {
	if m != nil {
		return m.Span
	}
	return nil
}

func (m *Diagnostic) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Diagnostic) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *Diagnostic) GetContextUrl() string {
	if m != nil {
		return m.ContextUrl
	}
	return ""
}

type ResolvedDiagnostic struct {
	CorpusPath           *CorpusPath `protobuf:"bytes,1,opt,name=corpus_path,json=corpusPath,proto3" json:"corpus_path,omitempty"`
	Diagnostic           *Diagnostic `protobuf:"bytes,2,opt,name=diagnostic,proto3" json:"diagnostic,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ResolvedDiagnostic) Reset()         { *m = ResolvedDiagnostic{} }
func (m *ResolvedDiagnostic) String() string { return proto.CompactTextString(m) }
func (*ResolvedDiagnostic) ProtoMessage()    {}
func (*ResolvedDiagnostic) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_1d80375ed42fe73a, []int{5}
}
func (m *ResolvedDiagnostic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedDiagnostic.Unmarshal(m, b)
}
func (m *ResolvedDiagnostic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedDiagnostic.Marshal(b, m, deterministic)
}
func (dst *ResolvedDiagnostic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedDiagnostic.Merge(dst, src)
}
func (m *ResolvedDiagnostic) XXX_Size() int {
	return xxx_messageInfo_ResolvedDiagnostic.Size(m)
}
func (m *ResolvedDiagnostic) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedDiagnostic.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedDiagnostic proto.InternalMessageInfo

func (m *ResolvedDiagnostic) GetCorpusPath() *CorpusPath {
	if m != nil {
		return m.CorpusPath
	}
	return nil
}

func (m *ResolvedDiagnostic) GetDiagnostic() *Diagnostic {
	if m != nil {
		return m.Diagnostic
	}
	return nil
}

type CorpusPath struct {
	Corpus               string   `protobuf:"bytes,1,opt,name=corpus,proto3" json:"corpus,omitempty"`
	Root                 string   `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CorpusPath) Reset()         { *m = CorpusPath{} }
func (m *CorpusPath) String() string { return proto.CompactTextString(m) }
func (*CorpusPath) ProtoMessage()    {}
func (*CorpusPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_1d80375ed42fe73a, []int{6}
}
func (m *CorpusPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CorpusPath.Unmarshal(m, b)
}
func (m *CorpusPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CorpusPath.Marshal(b, m, deterministic)
}
func (dst *CorpusPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CorpusPath.Merge(dst, src)
}
func (m *CorpusPath) XXX_Size() int {
	return xxx_messageInfo_CorpusPath.Size(m)
}
func (m *CorpusPath) XXX_DiscardUnknown() {
	xxx_messageInfo_CorpusPath.DiscardUnknown(m)
}

var xxx_messageInfo_CorpusPath proto.InternalMessageInfo

func (m *CorpusPath) GetCorpus() string {
	if m != nil {
		return m.Corpus
	}
	return ""
}

func (m *CorpusPath) GetRoot() string {
	if m != nil {
		return m.Root
	}
	return ""
}

func (m *CorpusPath) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type Link struct {
	Definition           []string  `protobuf:"bytes,3,rep,name=definition,proto3" json:"definition,omitempty"`
	Kind                 Link_Kind `protobuf:"varint,2,opt,name=kind,proto3,enum=kythe.proto.common.Link_Kind" json:"kind,omitempty"` // Deprecated: Do not use.
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Link) Reset()         { *m = Link{} }
func (m *Link) String() string { return proto.CompactTextString(m) }
func (*Link) ProtoMessage()    {}
func (*Link) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_1d80375ed42fe73a, []int{7}
}
func (m *Link) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Link.Unmarshal(m, b)
}
func (m *Link) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Link.Marshal(b, m, deterministic)
}
func (dst *Link) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Link.Merge(dst, src)
}
func (m *Link) XXX_Size() int {
	return xxx_messageInfo_Link.Size(m)
}
func (m *Link) XXX_DiscardUnknown() {
	xxx_messageInfo_Link.DiscardUnknown(m)
}

var xxx_messageInfo_Link proto.InternalMessageInfo

func (m *Link) GetDefinition() []string {
	if m != nil {
		return m.Definition
	}
	return nil
}

// Deprecated: Do not use.
func (m *Link) GetKind() Link_Kind {
	if m != nil {
		return m.Kind
	}
	return Link_DEFINITION
}

type MarkedSource struct {
	Kind                 MarkedSource_Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=kythe.proto.common.MarkedSource_Kind" json:"kind,omitempty"`
	PreText              string            `protobuf:"bytes,2,opt,name=pre_text,json=preText,proto3" json:"pre_text,omitempty"`
	Child                []*MarkedSource   `protobuf:"bytes,3,rep,name=child,proto3" json:"child,omitempty"`
	PostChildText        string            `protobuf:"bytes,4,opt,name=post_child_text,json=postChildText,proto3" json:"post_child_text,omitempty"`
	PostText             string            `protobuf:"bytes,5,opt,name=post_text,json=postText,proto3" json:"post_text,omitempty"`
	LookupIndex          uint32            `protobuf:"varint,6,opt,name=lookup_index,json=lookupIndex,proto3" json:"lookup_index,omitempty"`
	DefaultChildrenCount uint32            `protobuf:"varint,7,opt,name=default_children_count,json=defaultChildrenCount,proto3" json:"default_children_count,omitempty"`
	AddFinalListToken    bool              `protobuf:"varint,10,opt,name=add_final_list_token,json=addFinalListToken,proto3" json:"add_final_list_token,omitempty"`
	Link                 []*Link           `protobuf:"bytes,11,rep,name=link,proto3" json:"link,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MarkedSource) Reset()         { *m = MarkedSource{} }
func (m *MarkedSource) String() string { return proto.CompactTextString(m) }
func (*MarkedSource) ProtoMessage()    {}
func (*MarkedSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_1d80375ed42fe73a, []int{8}
}
func (m *MarkedSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarkedSource.Unmarshal(m, b)
}
func (m *MarkedSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarkedSource.Marshal(b, m, deterministic)
}
func (dst *MarkedSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarkedSource.Merge(dst, src)
}
func (m *MarkedSource) XXX_Size() int {
	return xxx_messageInfo_MarkedSource.Size(m)
}
func (m *MarkedSource) XXX_DiscardUnknown() {
	xxx_messageInfo_MarkedSource.DiscardUnknown(m)
}

var xxx_messageInfo_MarkedSource proto.InternalMessageInfo

func (m *MarkedSource) GetKind() MarkedSource_Kind {
	if m != nil {
		return m.Kind
	}
	return MarkedSource_BOX
}

func (m *MarkedSource) GetPreText() string {
	if m != nil {
		return m.PreText
	}
	return ""
}

func (m *MarkedSource) GetChild() []*MarkedSource {
	if m != nil {
		return m.Child
	}
	return nil
}

func (m *MarkedSource) GetPostChildText() string {
	if m != nil {
		return m.PostChildText
	}
	return ""
}

func (m *MarkedSource) GetPostText() string {
	if m != nil {
		return m.PostText
	}
	return ""
}

func (m *MarkedSource) GetLookupIndex() uint32 {
	if m != nil {
		return m.LookupIndex
	}
	return 0
}

func (m *MarkedSource) GetDefaultChildrenCount() uint32 {
	if m != nil {
		return m.DefaultChildrenCount
	}
	return 0
}

func (m *MarkedSource) GetAddFinalListToken() bool {
	if m != nil {
		return m.AddFinalListToken
	}
	return false
}

func (m *MarkedSource) GetLink() []*Link {
	if m != nil {
		return m.Link
	}
	return nil
}

type SymbolInfo struct {
	BaseName             string   `protobuf:"bytes,1,opt,name=base_name,json=baseName,proto3" json:"base_name,omitempty"`
	QualifiedName        string   `protobuf:"bytes,2,opt,name=qualified_name,json=qualifiedName,proto3" json:"qualified_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SymbolInfo) Reset()         { *m = SymbolInfo{} }
func (m *SymbolInfo) String() string { return proto.CompactTextString(m) }
func (*SymbolInfo) ProtoMessage()    {}
func (*SymbolInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_1d80375ed42fe73a, []int{9}
}
func (m *SymbolInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SymbolInfo.Unmarshal(m, b)
}
func (m *SymbolInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SymbolInfo.Marshal(b, m, deterministic)
}
func (dst *SymbolInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SymbolInfo.Merge(dst, src)
}
func (m *SymbolInfo) XXX_Size() int {
	return xxx_messageInfo_SymbolInfo.Size(m)
}
func (m *SymbolInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SymbolInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SymbolInfo proto.InternalMessageInfo

func (m *SymbolInfo) GetBaseName() string {
	if m != nil {
		return m.BaseName
	}
	return ""
}

func (m *SymbolInfo) GetQualifiedName() string {
	if m != nil {
		return m.QualifiedName
	}
	return ""
}

func init() {
	proto.RegisterType((*Fact)(nil), "kythe.proto.common.Fact")
	proto.RegisterType((*Point)(nil), "kythe.proto.common.Point")
	proto.RegisterType((*Span)(nil), "kythe.proto.common.Span")
	proto.RegisterType((*NodeInfo)(nil), "kythe.proto.common.NodeInfo")
	proto.RegisterMapType((map[string][]byte)(nil), "kythe.proto.common.NodeInfo.FactsEntry")
	proto.RegisterType((*Diagnostic)(nil), "kythe.proto.common.Diagnostic")
	proto.RegisterType((*ResolvedDiagnostic)(nil), "kythe.proto.common.ResolvedDiagnostic")
	proto.RegisterType((*CorpusPath)(nil), "kythe.proto.common.CorpusPath")
	proto.RegisterType((*Link)(nil), "kythe.proto.common.Link")
	proto.RegisterType((*MarkedSource)(nil), "kythe.proto.common.MarkedSource")
	proto.RegisterType((*SymbolInfo)(nil), "kythe.proto.common.SymbolInfo")
	proto.RegisterEnum("kythe.proto.common.Link_Kind", Link_Kind_name, Link_Kind_value)
	proto.RegisterEnum("kythe.proto.common.MarkedSource_Kind", MarkedSource_Kind_name, MarkedSource_Kind_value)
}

func init() { proto.RegisterFile("kythe/proto/common.proto", fileDescriptor_common_1d80375ed42fe73a) }

var fileDescriptor_common_1d80375ed42fe73a = []byte{
	// 947 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0xed, 0x8e, 0xda, 0x46,
	0x14, 0xad, 0xc1, 0x2c, 0x70, 0xd9, 0x0f, 0x77, 0xba, 0x8a, 0xbc, 0x8d, 0x92, 0x50, 0x57, 0x69,
	0x90, 0x52, 0xb1, 0xd5, 0x36, 0xad, 0xd2, 0x4a, 0x6d, 0xc4, 0x82, 0x51, 0xdd, 0xb0, 0x80, 0x06,
	0xaf, 0x9a, 0xe4, 0x8f, 0x65, 0xec, 0x81, 0x1d, 0x61, 0x66, 0xa8, 0x3d, 0x5e, 0x2d, 0x4f, 0xd1,
	0x5f, 0x7d, 0x83, 0xbe, 0x40, 0xdf, 0xa3, 0xef, 0xd1, 0x3e, 0x46, 0x35, 0x33, 0x66, 0x97, 0xa4,
	0xa4, 0xf9, 0xc5, 0xdc, 0x73, 0xcf, 0xbd, 0x73, 0x7c, 0xee, 0x35, 0x06, 0x7b, 0xb1, 0x16, 0x57,
	0xe4, 0x74, 0x95, 0x72, 0xc1, 0x4f, 0x23, 0xbe, 0x5c, 0x72, 0xd6, 0x56, 0x01, 0x42, 0x2a, 0xa3,
	0x83, 0xb6, 0xce, 0x38, 0x5f, 0x81, 0xd9, 0x0f, 0x23, 0x81, 0x10, 0x98, 0x2c, 0x5c, 0x12, 0xdb,
	0x68, 0x1a, 0xad, 0x3a, 0x56, 0x67, 0x74, 0x0c, 0x95, 0xeb, 0x30, 0xc9, 0x89, 0x5d, 0x6a, 0x1a,
	0xad, 0x7d, 0xac, 0x03, 0x87, 0x41, 0x65, 0xcc, 0x29, 0x13, 0xe8, 0x11, 0x34, 0xa6, 0x6b, 0x41,
	0x02, 0x3e, 0x9b, 0x65, 0x44, 0xa8, 0xca, 0x0a, 0x06, 0x09, 0x8d, 0x14, 0x22, 0x09, 0x09, 0x65,
	0x24, 0x60, 0xf9, 0x72, 0x4a, 0x52, 0xd5, 0xa5, 0x82, 0x41, 0x42, 0x43, 0x85, 0xa0, 0xcf, 0xe1,
	0x20, 0xe2, 0x49, 0xbe, 0x64, 0x9b, 0x1e, 0x65, 0x45, 0xd9, 0xd7, 0xa0, 0xee, 0xe2, 0xc4, 0x60,
	0x4e, 0x56, 0x21, 0x43, 0xa7, 0x50, 0xc9, 0x44, 0x98, 0xea, 0x8b, 0x1a, 0x67, 0x27, 0xed, 0xff,
	0x3e, 0x4d, 0x5b, 0x09, 0xc3, 0x9a, 0x87, 0x9e, 0x42, 0x99, 0xb0, 0x58, 0x5d, 0xfb, 0xbf, 0x74,
	0xc9, 0x72, 0xfe, 0x34, 0xa0, 0x36, 0xe4, 0x31, 0xf1, 0xd8, 0x8c, 0xa3, 0x1f, 0xa0, 0x32, 0x0b,
	0x23, 0x91, 0xd9, 0xa5, 0x66, 0xb9, 0xd5, 0x38, 0x7b, 0xb2, 0xab, 0x76, 0x43, 0x6e, 0x4b, 0xfb,
	0x32, 0x97, 0x89, 0x74, 0x8d, 0x75, 0x15, 0x7a, 0x08, 0x10, 0x93, 0x19, 0x65, 0x54, 0x50, 0xce,
	0xec, 0x8a, 0x72, 0x74, 0x0b, 0xf9, 0xf4, 0x39, 0xc0, 0x5d, 0x11, 0xb2, 0xa0, 0xbc, 0x20, 0xeb,
	0xc2, 0x78, 0x79, 0xdc, 0xed, 0xfb, 0xf7, 0xa5, 0xe7, 0xc6, 0xcf, 0x66, 0xcd, 0xb0, 0x4a, 0x78,
	0x4f, 0xd0, 0x68, 0x41, 0x84, 0xf3, 0x9b, 0x01, 0xd0, 0xa3, 0xe1, 0x9c, 0xf1, 0x4c, 0xd0, 0x08,
	0x7d, 0x09, 0x66, 0xb6, 0x0a, 0x59, 0xe1, 0x8f, 0xbd, 0x4b, 0xb4, 0x34, 0x12, 0x2b, 0x16, 0xb2,
	0xa1, 0xba, 0x24, 0x59, 0x16, 0xce, 0xf5, 0x35, 0x75, 0xbc, 0x09, 0x65, 0x26, 0x26, 0x22, 0xa4,
	0x49, 0xa6, 0xe6, 0x51, 0xc7, 0x9b, 0x50, 0x0e, 0x34, 0xe2, 0x4c, 0x90, 0x1b, 0x11, 0xe4, 0x69,
	0x62, 0x9b, 0xfa, 0xc9, 0x0a, 0xe8, 0x32, 0x4d, 0x9c, 0xdf, 0x0d, 0x40, 0x98, 0x64, 0x3c, 0xb9,
	0x26, 0xf1, 0x96, 0xb2, 0x17, 0xb2, 0x2e, 0x5d, 0xe5, 0x59, 0xb0, 0x0a, 0xc5, 0x55, 0x21, 0xf0,
	0xe1, 0x2e, 0x81, 0x5d, 0x45, 0x1b, 0x87, 0xe2, 0x4a, 0xf6, 0xdd, 0x9c, 0xd1, 0x8f, 0x00, 0xf1,
	0x6d, 0xbb, 0x62, 0xa2, 0x3b, 0xeb, 0xef, 0x2e, 0xc5, 0x5b, 0x15, 0xce, 0x00, 0xe0, 0xae, 0x33,
	0xba, 0x07, 0x7b, 0xba, 0x77, 0x61, 0x7a, 0x11, 0xc9, 0x77, 0x20, 0xe5, 0x5c, 0x14, 0x7e, 0xa8,
	0xb3, 0xc4, 0x94, 0x66, 0xed, 0x84, 0x3a, 0x3b, 0x7f, 0x18, 0x60, 0x0e, 0x28, 0x5b, 0xbc, 0x33,
	0xe8, 0x72, 0xb3, 0xfc, 0xf6, 0xa0, 0xd1, 0x37, 0x60, 0x2e, 0x68, 0xb1, 0x82, 0x87, 0x67, 0x0f,
	0x76, 0x09, 0x96, 0x7d, 0xda, 0x2f, 0x29, 0x8b, 0xcf, 0x4b, 0xb6, 0x81, 0x15, 0xdd, 0x79, 0x01,
	0xa6, 0x44, 0xd0, 0x21, 0x40, 0xcf, 0xed, 0x7b, 0x43, 0xcf, 0xf7, 0x46, 0x43, 0xeb, 0x23, 0x54,
	0x03, 0x73, 0xe0, 0x4d, 0x7c, 0xcb, 0x40, 0x07, 0x50, 0x97, 0xa7, 0xc0, 0xf3, 0xdd, 0x0b, 0xab,
	0x84, 0x0e, 0xa1, 0xee, 0x5d, 0x8c, 0x47, 0xd8, 0xef, 0x0c, 0x7d, 0xeb, 0xef, 0xaa, 0x5e, 0x13,
	0xe7, 0x1f, 0x13, 0xf6, 0x2f, 0xc2, 0x74, 0x41, 0xe2, 0x09, 0xcf, 0xd3, 0x88, 0xa0, 0xef, 0x0a,
	0x39, 0x86, 0x92, 0xf3, 0x78, 0x97, 0x9c, 0x6d, 0xbe, 0x92, 0xa5, 0x25, 0xa1, 0x13, 0xa8, 0xad,
	0x52, 0x12, 0xc8, 0x39, 0x6f, 0xd6, 0x65, 0x95, 0x12, 0x9f, 0xdc, 0x08, 0xf4, 0x2d, 0x54, 0xa2,
	0x2b, 0x9a, 0xc4, 0xea, 0xf9, 0x1b, 0x67, 0xcd, 0x0f, 0xb5, 0xc5, 0x9a, 0x8e, 0xbe, 0x80, 0xa3,
	0x15, 0xcf, 0x44, 0xa0, 0x22, 0xdd, 0x59, 0x2f, 0xd4, 0x81, 0x84, 0xbb, 0x12, 0x55, 0xfd, 0xef,
	0x43, 0x5d, 0xf1, 0x14, 0x43, 0xbf, 0x4c, 0x35, 0x09, 0xa8, 0xe4, 0x67, 0xb0, 0x9f, 0x70, 0xbe,
	0xc8, 0x57, 0x01, 0x65, 0x31, 0xb9, 0xb1, 0xf7, 0x9a, 0x46, 0xeb, 0x00, 0x37, 0x34, 0xe6, 0x49,
	0x08, 0x3d, 0x83, 0x7b, 0x31, 0x99, 0x85, 0x79, 0x52, 0x5c, 0x95, 0x12, 0x16, 0x44, 0x3c, 0x67,
	0xc2, 0xae, 0x2a, 0xf2, 0x71, 0x91, 0xed, 0x16, 0xc9, 0xae, 0xcc, 0xa1, 0x53, 0x38, 0x0e, 0xe3,
	0x38, 0x98, 0x51, 0x16, 0x26, 0x41, 0x42, 0xe5, 0xfd, 0x7c, 0x41, 0x98, 0x0d, 0x4d, 0xa3, 0x55,
	0xc3, 0x1f, 0x87, 0x71, 0xdc, 0x97, 0xa9, 0x01, 0xcd, 0x84, 0x2f, 0x13, 0xf2, 0xed, 0x4b, 0x28,
	0x5b, 0xd8, 0x0d, 0xe5, 0x82, 0xfd, 0xbe, 0x59, 0x63, 0xc5, 0x72, 0xfe, 0x32, 0x8a, 0x19, 0x57,
	0xa1, 0x7c, 0x3e, 0x7a, 0xa5, 0x87, 0xeb, 0xbf, 0x1e, 0xbb, 0x7a, 0xb8, 0xe3, 0x0e, 0xee, 0x5c,
	0xb8, 0xbe, 0x8b, 0xd5, 0x70, 0xc1, 0xeb, 0xb9, 0x43, 0xdf, 0xeb, 0x7b, 0x2e, 0xb6, 0xca, 0xa8,
	0x01, 0xd5, 0xee, 0x68, 0xe8, 0xbb, 0xaf, 0x7c, 0xcb, 0x44, 0x47, 0xd0, 0x50, 0xfb, 0xd1, 0x19,
	0x78, 0x6f, 0x5c, 0x6c, 0x55, 0xd0, 0x03, 0x38, 0xb9, 0x2d, 0x0e, 0x06, 0xa3, 0xd1, 0xcb, 0xcb,
	0x71, 0x70, 0xfe, 0x3a, 0x50, 0x98, 0xb5, 0x87, 0x3e, 0x81, 0xa3, 0x77, 0xc1, 0x2a, 0x7a, 0x0a,
	0x4f, 0xde, 0x5b, 0x13, 0xfc, 0xe2, 0xf9, 0x3f, 0x05, 0x3d, 0xb7, 0xdf, 0xb9, 0x1c, 0xf8, 0x13,
	0xab, 0xf6, 0x76, 0x07, 0xa9, 0xb8, 0x67, 0xd5, 0x9d, 0x31, 0xc0, 0x64, 0xbd, 0x9c, 0xf2, 0x44,
	0xfd, 0x7d, 0xde, 0x87, 0xfa, 0x34, 0xcc, 0x48, 0xb0, 0xf5, 0x41, 0xa9, 0x49, 0x60, 0x28, 0x3f,
	0x2a, 0x8f, 0xe1, 0xf0, 0xd7, 0x3c, 0x4c, 0xe8, 0x8c, 0x92, 0x58, 0x33, 0xf4, 0x3e, 0x1d, 0xdc,
	0xa2, 0x92, 0x76, 0xfe, 0x0c, 0x1e, 0x45, 0x7c, 0xd9, 0x9e, 0x73, 0x3e, 0x4f, 0x48, 0x3b, 0x26,
	0xd7, 0x82, 0xf3, 0x24, 0xdb, 0x76, 0x75, 0x6c, 0xbc, 0x39, 0xd2, 0xc6, 0x06, 0x73, 0x1e, 0x28,
	0x68, 0xba, 0xa7, 0x7e, 0xbe, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x8c, 0x92, 0x98, 0x04,
	0x07, 0x00, 0x00,
}
