package(default_visibility = ["//kythe:default_visibility"])

java_test(
    name = "kythe_uri_test",
    srcs = ["KytheURITest.java"],
    test_class = "com.google.devtools.kythe.util.KytheURITest",
    deps = [
        "//kythe/java/com/google/devtools/kythe/util",
        "//kythe/proto:storage_proto_java",
        "//third_party:junit4",
        "//third_party/proto:protobuf_java",
    ],
)
