#!/bin/bash -e
#
# Copyright 2017 The Kythe Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o pipefail
BROWSE_PORT="${BROWSE_PORT:-8080}"
KYTHE="${KYTHE:-/opt/kythe}"

rm -f -- graphstore/* tables/*
mkdir -p graphstore tables
# Read JSON entries from standard in to a graphstore.
"$KYTHE/tools/entrystream" --read_format=json \
  | "$KYTHE/tools/write_entries" -graphstore graphstore
# Convert the graphstore to serving tables.
"$KYTHE/tools/write_tables" -graphstore graphstore -out=tables
# Host the browser UI.
"$KYTHE/tools/http_server" -serving_table tables \
  -public_resources="$KYTHE/web/ui" \
  -listen=":${BROWSE_PORT}"
