// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kythe/go/util/riegeli/riegeli_test.proto

package riegeli_test_go_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Simple struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Simple) Reset()         { *m = Simple{} }
func (m *Simple) String() string { return proto.CompactTextString(m) }
func (*Simple) ProtoMessage()    {}
func (*Simple) Descriptor() ([]byte, []int) {
	return fileDescriptor_b786c6e75369a723, []int{0}
}

func (m *Simple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Simple.Unmarshal(m, b)
}
func (m *Simple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Simple.Marshal(b, m, deterministic)
}
func (m *Simple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Simple.Merge(m, src)
}
func (m *Simple) XXX_Size() int {
	return xxx_messageInfo_Simple.Size(m)
}
func (m *Simple) XXX_DiscardUnknown() {
	xxx_messageInfo_Simple.DiscardUnknown(m)
}

var xxx_messageInfo_Simple proto.InternalMessageInfo

func (m *Simple) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type Complex struct {
	Str                  *string          `protobuf:"bytes,1,opt,name=str" json:"str,omitempty"`
	I32                  *int32           `protobuf:"varint,2,opt,name=i32" json:"i32,omitempty"`
	I64                  *int64           `protobuf:"varint,3,opt,name=i64" json:"i64,omitempty"`
	Bits                 []byte           `protobuf:"bytes,4,opt,name=bits" json:"bits,omitempty"`
	Rep                  []string         `protobuf:"bytes,5,rep,name=rep" json:"rep,omitempty"`
	SimpleNested         *Simple          `protobuf:"bytes,6,opt,name=simple_nested,json=simpleNested" json:"simple_nested,omitempty"`
	Group                []*Complex_Group `protobuf:"group,7,rep,name=Group,json=group" json:"group,omitempty"`
	ComplexNested        *Complex         `protobuf:"bytes,8,opt,name=complex_nested,json=complexNested" json:"complex_nested,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Complex) Reset()         { *m = Complex{} }
func (m *Complex) String() string { return proto.CompactTextString(m) }
func (*Complex) ProtoMessage()    {}
func (*Complex) Descriptor() ([]byte, []int) {
	return fileDescriptor_b786c6e75369a723, []int{1}
}

func (m *Complex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Complex.Unmarshal(m, b)
}
func (m *Complex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Complex.Marshal(b, m, deterministic)
}
func (m *Complex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Complex.Merge(m, src)
}
func (m *Complex) XXX_Size() int {
	return xxx_messageInfo_Complex.Size(m)
}
func (m *Complex) XXX_DiscardUnknown() {
	xxx_messageInfo_Complex.DiscardUnknown(m)
}

var xxx_messageInfo_Complex proto.InternalMessageInfo

func (m *Complex) GetStr() string {
	if m != nil && m.Str != nil {
		return *m.Str
	}
	return ""
}

func (m *Complex) GetI32() int32 {
	if m != nil && m.I32 != nil {
		return *m.I32
	}
	return 0
}

func (m *Complex) GetI64() int64 {
	if m != nil && m.I64 != nil {
		return *m.I64
	}
	return 0
}

func (m *Complex) GetBits() []byte {
	if m != nil {
		return m.Bits
	}
	return nil
}

func (m *Complex) GetRep() []string {
	if m != nil {
		return m.Rep
	}
	return nil
}

func (m *Complex) GetSimpleNested() *Simple {
	if m != nil {
		return m.SimpleNested
	}
	return nil
}

func (m *Complex) GetGroup() []*Complex_Group {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *Complex) GetComplexNested() *Complex {
	if m != nil {
		return m.ComplexNested
	}
	return nil
}

type Complex_Group struct {
	GrpStr               *string  `protobuf:"bytes,1,opt,name=grp_str,json=grpStr" json:"grp_str,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Complex_Group) Reset()         { *m = Complex_Group{} }
func (m *Complex_Group) String() string { return proto.CompactTextString(m) }
func (*Complex_Group) ProtoMessage()    {}
func (*Complex_Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_b786c6e75369a723, []int{1, 0}
}

func (m *Complex_Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Complex_Group.Unmarshal(m, b)
}
func (m *Complex_Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Complex_Group.Marshal(b, m, deterministic)
}
func (m *Complex_Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Complex_Group.Merge(m, src)
}
func (m *Complex_Group) XXX_Size() int {
	return xxx_messageInfo_Complex_Group.Size(m)
}
func (m *Complex_Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Complex_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Complex_Group proto.InternalMessageInfo

func (m *Complex_Group) GetGrpStr() string {
	if m != nil && m.GrpStr != nil {
		return *m.GrpStr
	}
	return ""
}

func init() {
	proto.RegisterType((*Simple)(nil), "kythe.proto.riegeli_test.Simple")
	proto.RegisterType((*Complex)(nil), "kythe.proto.riegeli_test.Complex")
	proto.RegisterType((*Complex_Group)(nil), "kythe.proto.riegeli_test.Complex.Group")
}

func init() {
	proto.RegisterFile("kythe/go/util/riegeli/riegeli_test.proto", fileDescriptor_b786c6e75369a723)
}

var fileDescriptor_b786c6e75369a723 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0x49, 0xb7, 0xbb, 0xab, 0x63, 0x2b, 0x12, 0x90, 0x06, 0xf1, 0x10, 0x7b, 0x31, 0xa7,
	0x5d, 0x58, 0xc5, 0x9b, 0x17, 0x45, 0xf4, 0xe4, 0x21, 0xbd, 0x79, 0x59, 0xfc, 0x33, 0xc4, 0xe0,
	0xb6, 0x09, 0xd9, 0x14, 0xf4, 0x93, 0xfa, 0x75, 0x24, 0xc9, 0x16, 0x7b, 0x29, 0x3d, 0xe5, 0x65,
	0xe6, 0xbd, 0xc7, 0x2f, 0x01, 0xf1, 0xf5, 0xe3, 0x3f, 0xb1, 0x56, 0xa6, 0x5e, 0x7b, 0xdd, 0xd5,
	0x4e, 0xa3, 0xc2, 0x4e, 0x6f, 0xce, 0xd6, 0x63, 0xef, 0x2b, 0xeb, 0x8c, 0x37, 0x94, 0x45, 0x67,
	0xba, 0x54, 0xdb, 0xfb, 0xf9, 0x39, 0x14, 0x0b, 0xbd, 0xb4, 0x1d, 0x52, 0x0a, 0xe3, 0xd5, 0xeb,
	0x12, 0x19, 0xe1, 0x44, 0x1c, 0xca, 0xa8, 0xe7, 0xbf, 0x23, 0x28, 0xef, 0x4d, 0x58, 0x7f, 0xd3,
	0x13, 0xc8, 0x7a, 0xef, 0x86, 0x75, 0x90, 0x61, 0xa2, 0xaf, 0x1a, 0x36, 0xe2, 0x44, 0xe4, 0x32,
	0xc8, 0x38, 0xb9, 0xb9, 0x66, 0x19, 0x27, 0x22, 0x93, 0x41, 0x86, 0xd6, 0x37, 0xed, 0x7b, 0x36,
	0xe6, 0x44, 0x4c, 0x64, 0xd4, 0xc1, 0xe5, 0xd0, 0xb2, 0x9c, 0x67, 0xa1, 0xc9, 0xa1, 0xa5, 0x0f,
	0x30, 0xed, 0x23, 0x45, 0xbb, 0xc2, 0xde, 0xe3, 0x07, 0x2b, 0x38, 0x11, 0x47, 0x0d, 0xaf, 0x76,
	0x71, 0x57, 0x09, 0x5a, 0x4e, 0x52, 0xec, 0x39, 0xa6, 0xe8, 0x2d, 0xe4, 0xca, 0x99, 0xb5, 0x65,
	0x25, 0xcf, 0x04, 0x34, 0x97, 0xbb, 0xe3, 0xc3, 0xa3, 0xaa, 0xc7, 0x60, 0x97, 0x29, 0x45, 0x9f,
	0xe0, 0xf8, 0x3d, 0xcd, 0x37, 0x18, 0x07, 0x11, 0xe3, 0x62, 0x6f, 0x8f, 0x9c, 0x0e, 0xc1, 0x04,
	0x72, 0xc6, 0x21, 0x8f, 0xcd, 0x74, 0x06, 0xa5, 0x72, 0xb6, 0xfd, 0xff, 0xb8, 0x42, 0x39, 0xbb,
	0xf0, 0xee, 0x6e, 0xf6, 0x72, 0xba, 0x5d, 0xd4, 0x2a, 0xd3, 0xc6, 0xfa, 0xbf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xe1, 0xac, 0x35, 0x61, 0xd5, 0x01, 0x00, 0x00,
}
