load("//tools:build_rules/shims.bzl", "go_binary")

package(default_visibility = ["//kythe:default_visibility"])

go_binary(
    name = "cmakedefines",
    srcs = ["cmakedefines.go"],
    visibility = ["//visibility:public"],
)
