load(":asciidoc_with_verifier.bzl", "asciidoc_with_verifier")

package(default_visibility = ["//kythe:default_visibility"])

asciidoc_with_verifier(
    name = "schema",
    src = "schema.txt",
)

asciidoc_with_verifier(
    name = "callgraph",
    src = "callgraph.txt",
)

asciidoc_with_verifier(
    name = "verifierstyle",
    src = "verifierstyle.txt",
)
