load("//tools:build_rules/go.bzl", "go_package_library")

package(default_visibility = ["//kythe:default_visibility"])

go_package_library(
    name = "profile",
    srcs = ["profile.go"],
    deps = [
        "//kythe/go/platform/vfs",
    ],
)
