package(default_visibility = ["//kythe:default_visibility"])

java_test(
    name = "compilation_unit_file_tree_test",
    size = "small",
    srcs = ["CompilationUnitFileTreeTest.java"],
    test_class = "com.google.devtools.kythe.platform.java.filemanager.CompilationUnitFileTreeTest",
    deps = [
        "//external:guava",
        "//external:junit4",
        "//kythe/java/com/google/devtools/kythe/platform/java/filemanager",
        "//kythe/proto:analysis_proto_java",
    ],
)
