package(default_visibility = ["//kythe:default_visibility"])

filegroup(
    name = "write_entries",
    srcs = ["//kythe/go/storage/tools/write_entries"],
)

filegroup(
    name = "read_entries",
    srcs = ["//kythe/go/storage/tools/read_entries"],
)

filegroup(
    name = "triples",
    srcs = ["//kythe/go/storage/tools/triples"],
)

filegroup(
    name = "directory_indexer",
    srcs = ["//kythe/go/storage/tools/directory_indexer"],
)
