load("//tools:build_rules/go.bzl", "go_package")

package(default_visibility = ["//kythe:default_visibility"])

go_package(
    test_deps = [
        "@go_x_net//:html",
    ],
    deps = [
        "@go_x_net//:html",
    ],
)
