load("//tools/build_rules/go", "go_library")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "html",
    srcs = [
        "html.go",
    ],
    deps = [
        "//third_party/go:html",
    ],
)
