steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', '${_REPO_NAME}', '/workspace/code']
- name: 'ubuntu'
  args: ['mkdir', '/workspace/out']
- name: 'gcr.io/kythe-public/kythe-javac-extractor-artifacts'
  volumes:
    - name: 'kythe_extractors'
      path: '/opt/kythe/extractors/'
- name: 'gcr.io/kythe-public/build-preprocessor'
  args: ['/workspace/code/pom.xml']
- name: 'gcr.io/cloud-builders/mvn'
  args:
    - 'clean'
    - 'compile'
    - '-X'
    - '-f'
    - '/workspace/code/pom.xml'
    - '-Dmaven.compiler.forceJavacCompilerUse=true'
    - '-Dmaven.compiler.fork=true'
    - '-Dmaven.compiler.executable=/opt/kythe/extractors/javac-wrapper.sh'
  env:
    - 'KYTHE_CORPUS=mvnpoctest'
    -  'KYTHE_OUTPUT_DIRECTORY=/workspace/out'
    - 'KYTHE_OUTPUT_FILE=/workspace/out/test.kzip'
    - 'KYTHE_ROOT_DIRECTORY=/workspace/code'
    - 'JAVAC_EXTRACTOR_JAR=/opt/kythe/extractors/javac_extractor.jar'
    - 'REAL_JAVAC=/usr/bin/javac'
    - 'TMPDIR=/workspace/out'
    - 'KYTHE_JAVA_RUNTIME_OPTIONS=-Xbootclasspath/p:/opt/kythe/extractors/javac9_tools.jar'
  volumes:
    - name: 'kythe_extractors'
      path: '/opt/kythe/extractors/'
artifacts:
  objects:
    location: 'gs://${_BUCKET_NAME}/'
    paths:
      - '/workspace/out/javac-extractor.err'
      - '/workspace/out/test.kzip'

