#!/bin/bash
# Copyright 2015 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script wraps the `campfire` tool. It calls it with options and
# tool paths appropriate for the kythe-campfire Docker container.
#
# The campfire root is set through the CAMPFIRE_ROOT environment variables; if
# it is unset, $PWD will be assumed to be the root.
#
# On exit, the campfire root directory will be recursively chown'd to the root
# directory's permissions. This mostly fixes the issue with campfire being run
# as root inside the Docker container, creating root-owned build artifacts.
#
# Usage: campfire-wrapper [campfire_args...]

if [ -n "$CAMPFIRE_ROOT" ]; then
  cd "$CAMPFIRE_ROOT" || exit $?
fi
CAMPFIRE_ROOT="$PWD"

cleanup() {
  fix_permissions "$CAMPFIRE_ROOT"
}
trap cleanup EXIT ERR INT

if [[ "$1" == "update_modules" ]]; then
  ./buildtools/update_modules.sh
elif [[ "$1" == "build_update_modules" ]]; then
  ./buildtools/update_modules.sh --build_only
else
  ./campfire "$@"
fi
