package(default_visibility = ["//visibility:public"])

filegroup(
    name = "bazel_go_extractor",
    srcs = ["//kythe/go/extractors/cmd/bazel/bazel_go_extractor"],
)

filegroup(
    name = "extract_kzip",
    srcs = ["//kythe/go/extractors/cmd/bazel/extract_kzip"],
)
