load("//tools/build_rules/go", "go_library")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "vnameutil",
    srcs = [
        "rewrite.go",
    ],
    deps = [
        "//kythe/proto:storage_proto",
    ],
)
