package(default_visibility = ["//visibility:public"])

licenses(["unencumbered"])  # Authored by Google, Apache 2.0

exports_files(glob(["*"]))

filegroup(
    name = "grep-includes",
    srcs = ["dummy.sh"],
)
