package(
    default_visibility = ["//visibility:public"],
)

exports_files([
    "external_tools_configure.bzl",
    "external_tools_toolchain.bzl",
])

toolchain_type(name = "external_tools_toolchain_type")
