load("//tools/build_rules/go", "go_library")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "delimited",
    srcs = [
        "delimited.go",
    ],
    deps = [
        "//third_party/go:protobuf",
    ],
)
