load("/tools/build_rules/go", "go_package")

package(default_visibility = ["//kythe:default_visibility"])

go_package(
    deps = [
        "//kythe/go/platform/vfs",
        "//third_party/go/src/golang.org/x/net/context",
        "//third_party/go/src/golang.org/x/oauth2",
        "//third_party/go/src/golang.org/x/oauth2/google",
        "//third_party/go/src/google.golang.org/cloud",
    ],
)
