#!/bin/bash -e
#
# Copyright 2018 The Kythe Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Wrapper script to run Bazel via Bazelisk.
#
# Transforms USE_BAZEL_VERSION=min to USE_BAZEL_VERSION=$(<.bazelminversion).
# The .bazelminversion file may be in the current working directory or any
# parent directory.  The first readable file found will be used; if none are
# found, USE_BAZEL_VERSION is unset to fallback to a .bazelversion file or using
# 'latest'.

if [[ "$USE_BAZEL_VERSION" == "min" ]]; then
  dir="$PWD"
  while true; do
    if [[ -r "$dir/.bazelminversion" ]]; then
      USE_BAZEL_VERSION="$(<"$dir/.bazelminversion")"
      break
    elif [[ "$dir" == "/" ]]; then
      echo "WARNING: unable to find .bazelminversion file in cwd or above" >&2
      unset USE_BAZEL_VERSION
      break
    fi
    dir="$(dirname "$dir")"
  done
fi

exec bazelisk "$@"
