steps:
- name: gcr.io/cloud-builders/gsutil
  id: 'Fetch secrets'
  args:
  - cp
  - gs://kythe-buildbot/secrets.tar.enc
  - secrets.tar.enc
# Decrypt retrieved credentials.
# https://cloud.google.com/cloud-build/docs/securing-builds/use-encrypted-secrets-credentials
- name: gcr.io/cloud-builders/gcloud
  id: 'Decrypt secrets'
  args:
  - kms
  - decrypt
  - --location=global
  - --keyring=Buildbot
  - --key=secrets
  - --ciphertext-file=secrets.tar.enc
  - --plaintext-file=secrets.tar
- name: gcr.io/cloud-builders/docker
  id: 'Build image'
  args:
  - build
  - -t
  - gcr.io/$PROJECT_ID/buildbot.$_VERSION
  - .
- name: gcr.io/cloud-builders/docker
  id: 'Push image'
  args:
  - push
  - gcr.io/$PROJECT_ID/buildbot.$_VERSION
timeout: 30m
images:
  - gcr.io/$PROJECT_ID/buildbot.$_VERSION
substitutions:
  _VERSION: v1
