package(default_visibility = ["//visibility:public"])

java_library(
    name = "common",
    srcs = [
        "FormattingLogger.java",
        "PathUtil.java",
    ],
    deps = [
        "//third_party/guava",
    ],
)
