licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "edges",
    hdrs = ["edges.h"],
    srcs = ["edges.cc"],
    copts = [
        "-Wno-non-virtual-dtor",
        "-Wno-unused-variable",
        "-Wno-implicit-fallthrough",
    ],
    deps = [],
)

cc_library(
    name = "facts",
    hdrs = ["facts.h"],
    srcs = ["facts.cc"],
    copts = [
        "-Wno-non-virtual-dtor",
        "-Wno-unused-variable",
        "-Wno-implicit-fallthrough",
    ],
    deps = [],
)

