load("//tools:build_rules/shims.bzl", "go_library")

package(default_visibility = ["//kythe:default_visibility"])

go_library(
    name = "sortutil",
    srcs = ["sortutil.go"],
    visibility = [
        "//kythe:default_visibility",
        "//third_party/beam:__pkg__",
    ],
)
