load("@io_bazel_rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//kythe:default_visibility"])

go_library(
    name = "zip",
    srcs = ["fs.go"],
    deps = ["//kythe/go/platform/vfs"],
)
