load("//tools:build_rules/shims.bzl", "go_library")

package(default_visibility = ["//kythe:default_visibility"])

go_library(
    name = "zip",
    srcs = ["fs.go"],
    importpath = "kythe.io/kythe/go/platform/vfs/zip",
    deps = ["//kythe/go/platform/vfs"],
)
