package(default_visibility = ["//kythe:default_visibility"])

java_test(
    name = "archive_test",
    srcs = [
        "ArchiveTest.java",
    ],
    deps = [
        "//kythe/java/com/google/devtools/kythe/extractors/shared",
        "//kythe/java/com/google/devtools/kythe/platform/indexpack",
        "//kythe/java/com/google/devtools/kythe/util",
        "//kythe/proto:analysis_proto_java",
        "//kythe/proto:storage_proto_java",
        "//third_party:junit4",
        "//third_party/guava",
        "//third_party/proto:protobuf_java",
    ],
)
