load("//tools:build_rules/shims.bzl", "go_library")

package(default_visibility = ["//kythe:default_visibility"])

go_library(
    name = "md",
    srcs = ["md.go"],
    importpath = "kythe.io/kythe/go/util/md",
)
