load("//tools:build_rules/go.bzl", "go_package")

package(default_visibility = ["//kythe:default_visibility"])

go_package(
    deps = [
        "//kythe/go/storage/keyvalue",
        "//third_party/go/src/github.com/golang/protobuf/proto",
        "@go_x_net//:context",
    ],
)
