package(default_visibility = ["//visibility:public"])

filegroup(
    name = "http_server",
    srcs = ["//kythe/go/serving/tools/http_server"],
)

filegroup(
    name = "kythe",
    srcs = ["//kythe/go/serving/tools/kythe"],
)

filegroup(
    name = "kwazthis",
    srcs = ["//kythe/go/serving/tools/kwazthis"],
)

filegroup(
    name = "write_tables",
    srcs = ["//kythe/go/serving/tools/write_tables"],
)
