name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "43 7 * * 0"
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 7.1.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: "bazel build //..."
