load("//tools:build_rules/shims.bzl", "go_library")

package(default_visibility = ["//kythe:default_visibility"])

go_library(
    name = "locked",
    srcs = ["locked.go"],
    importpath = "kythe.io/kythe/go/platform/kcd/locked",
    deps = ["//kythe/go/platform/kcd"],
)
