load("//tools:build_rules/go.bzl", "go_package_library")

package(default_visibility = ["//kythe:default_visibility"])

go_package_library(
    name = "locked",
    srcs = ["locked.go"],
    deps = [
        "//kythe/go/platform/kcd",
    ],
)
